### PR TITLE
i3: replace deprecated options with new versions

### PR DESCRIPTION
**Pull request by yorickvP**
Encountered these when using 'sway' with this module.  They are compatible with i3.

### CODE REVIEW

**Comment by kalbasit** [comment]
There's a PR for sway support: #829
I'm not sure if this one duplicates it.

**Comment by jonringer** [comment]
no, that PR adds an i3-sway module. This is updating some of the options

**Comment by alexarice** [comment]
These flags are fixed for sway in my pr though I am not sure how close that is to merging and I guess the flags should be fixed for i3 as well

**Comment by mweinelt** [comment]
The change is minimal enough that it could go in now and you'd just rebase on top of that. But indeed your pr is quite far along. I've only tested the sway side of things though.

**Comment by alexarice** [comment]
> The change is minimal enough that it could go in now and you'd just rebase on top of that. But indeed your pr is quite far along. I've only tested the sway side of things though.

There is an i3 test that suggests I have not messed up the config, but yes this should be easy enough to rebase on. on this note, this pr might need to modify the i3 test?

**Comment by rycee** [comment]
I've merged #829 now but if the changes here are still necessary I'd be happy to merge once the PR has been updated.

**Comment by teto** [comment]
Still need a rebase apparently

**Comment by yorickvP** [comment]
I no longer use i3, and I think it works even with the deprecated options, so these changes are no longer necessary to me.

**Pull request closed without merging**
