### PR TITLE
home-manager: add sessionNixPath

### PR DESCRIPTION
**Pull request by happysalada**
enable the management of a session's NIX_PATH with home-manager

### Checklist

- [x] Change is backwards compatible.

- [ ] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

A couple of comments

this PR is a result of the discussion here.
https://github.com/nix-community/home-manager/pull/1564

I wasn't sure what to put as examples in the sessionNixPath, that's why I added the $HOME part.
When I tried to put `${cfg.home.homeDirectory}` it didn't work complaining that there was no home option.

It looks like my editor changed the format a bit on the second block of the commit. If it's a problem, just let me know and I'll change it manually.

@cole-h @rycee When you have a bit of time, let me know.

### CODE REVIEW

**Comment by teto** [comment]
you can already use nix.nixPath https://search.nixos.org/options?channel=unstable&show=nix.nixPath&from=0&size=30&sort=relevance&query=nix , or home.sessionVariables. Also NIX_PATH is going away in the next nix version so I dont think we should include this.

**Comment by happysalada** [comment]
@teto Thanks for taking the time to comment!

I didn't know that nixPath was going away.
I'm running into some problems with the nixPath and nix-darwin, but I guess, the problem should be solved there.

Thanks!

**Comment by andir** [comment]
>  Also NIX_PATH is going away in the next nix version so I dont think we should include this.

@teto do you have some source for that? This would kill backwards compat with a lot of things....

**Comment by teto** [comment]
flakes can't rely on environment variables to preserve caching so it may live on as an `--impure` artifact but I can't imagine it being recommended

**Pull request closed without merging**
