### PR TITLE
Add flake for referencing NixOS module

### LINKED ISSUE #1080: home-manager channel not compatible with Nix-2.4pre…
The latest version of the Nix tools at `nixos.nixFlakes` is not compatible with the channel tarballs. This is not a big problem as `<home-manager>` can refer to a local git checkout. I suppose the solution is to migrate to Nix flakes when the RFC clears and the tools stabilize.

```
$ nix-channel --update

these derivations will be built:
  /nix/store/…-home-manager.drv
building '/nix/store/…-home-manager.drv'...
error: unsupported builtin function 'unpack-channel'
builder for '/nix/store/…-home-manager.drv' failed with exit code 1
error: build of '/nix/store/…-home-manager.drv' failed
error: program '/nix/store/…-nix-2.4pre20200220_4a4521f/bin/nix-build' failed with
exit code 100
```

### PR DESCRIPTION
**Pull request by ehmry**
### Description

Make the NixOS option "home-manager.useGlobalPkgs" default to true
to maintain pure evaulation.

Fix #1080

---

The flake can be tested with the command `nix flake check`, which evaluates the NixOS module and builds `pkgs.home-manager`.

### Checklist

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/rycee/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/rycee/home-manager/blob/master/CONTRIBUTING.md#commits) for more information and [recent commit messages](https://github.com/rycee/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/rycee/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [x] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by teto** [comment]
do we really need the lock file ? other PRs do more to enforce home-manager works with restrict-eval etc. Have you tested this ?

**Comment by ehmry** [comment]
The flake contains a evaulation check, and for determinism this check must evaulated against some fixed version of NixOS. The nixpkgs input is only used for this check.

**Comment by bqv** [comment]
This needs a less destructive rebase, and then ideally squashing into one commit

**Comment by kalbasit** [comment]
flake.lock was committed, however, it remains in .gitignore

**Comment by berbiche** [comment]
@ehmry Is this still relevant?

**Comment by ehmry** [comment]
Meh.

**Pull request closed without merging**
