### PR TITLE
direnv: hopefully final nushell fix

### PR DESCRIPTION
**Pull request by K900**
### Description

I hate this.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

### CODE REVIEW

**Comment by rycee** [comment]
I fixed the test case and merged to master now. Hope it works better now! Have to go sleep so will check back tomorrow.

**Comment by nyabinary** [comment]
This breaks nushell as it overrides the default env.nu breaking the behavior of nushell in general isn't there a way to just append the direnv stuff instead of overwriting the entire env.nu file?

**Comment by K900** [comment]
No it doesn't? That's why the mkAfter is there.

**Comment by nyabinary** [comment]
> No it doesn't? That's why the mkAfter is there.

https://github.com/nix-community/home-manager/issues/5527
https://github.com/nushell/nushell/issues/13174

Does for me I just want to add a alias and stuff in my config and it overrides the entire default env.nu already in place instead of appending to it.

**Comment by K900** [comment]
That's unrelated to this change though?

**Comment by nyabinary** [comment]
> That's unrelated to this change though?

But the direnv thing is broken *in general* because if you enable the direnv support for nushell it currently breaks nushell:
image
Pops up a nu::shell::non_zero_exit_code when normally its not supposed to do that :P

**Comment by K900** [comment]
That has nothing to do with direnv, and it _is_ supposed to do that starting with Nushell 0.98 (see the original chain of PRs)

**Pull request merged**
