### PR TITLE
nixos: use `lib` argument instead of `pkgs.lib`

### PR DESCRIPTION
**Pull request by ThinkChaos**
### Description

This allows users to pass a lib with custom attributes and have those available to custom HM modules.

EDIT: marked as draft since it doesn't work and I was testing wrong.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by ambroisie** [comment]
@ThinkChaos are you still working on this MR?

**Comment by ncfavier** [comment]
This is related to https://github.com/NixOS/nixpkgs/pull/157056 and in particular could not work with the NixOS module until https://github.com/NixOS/nixpkgs/pull/210976 was merged. Should be fine now.

I'll leave the decision to @rycee though since this has raised some sort of ontological debate about the nature of `lib`.

**Comment by ThinkChaos** [comment]
Yeah I spent a fair bit of time trying to get it to work but stopped. The main blocker was me not understand how the modules system is implemented well enough!  
I'll give it another shot with a newer nixpkgs.

**Comment by ThinkChaos** [comment]
Tried this change again using https://github.com/NixOS/nixpkgs/commit/7067edc68c035e21780259ed2d26e1f164addaa2 and unfortunately, it doesn't work. At least with my test setup.  

I know HM is seeing my already extended lib properly because if I manually merge my extras, like the following snippet, it works.  
`extendedLib = [...] // { inherit (lib) myCustomPrefix; };`

So I'm wondering if I'm extending `nixpkgs.lib` wrong.  
Here's how I do it:
```nix
{
  lib = inputs.nixpkgs.lib.extend (self: super: {
    myCustomPrefix = import ./lib { inherit inputs; lib = self.makeExtensible (_: self); };
  });
}
```
And `home-manager.extraSpecialArgs.lib` ends up being the result of `self.makeExtensible (_: self);`.  
My understanding is that with https://github.com/NixOS/nixpkgs/pull/210976, my use of `self.makeExtensible` is now redundant, and removing doesn't seem to break anything. But that also means that that PR doesn't solve anything for me.

Is there anything obviously wrong with this setup?

**Comment by ncfavier** [comment]
What do you mean "it doesn't work"? Is there an error?

You shouldn't need to call `self.makeExtensible`, just use `lib = self;`.

**Comment by ThinkChaos** [comment]
Here's a flake that doesn't work:
```nix
{
  inputs =
  {
    nixpkgs.url = github:NixOS/nixpkgs/7067edc68c035e21780259ed2d26e1f164addaa2;

    home-manager = {
      url = github:ThinkChaos/home-manager/4833c849e3cbc1072e2415e3507671c8c577705e;
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, ... }@inputs:
  let
    lib = inputs.nixpkgs.lib.extend (self: super: {
      myCustomPrefix = { myCustomAttr = "not a bool"; };
    });

    user = "me";
  in
  {
    nixosConfigurations = {
      test = lib.nixosSystem {
        system = "x86_64-linux";

        modules = [
          inputs.home-manager.nixosModule {
            home-manager = {
              extraSpecialArgs = { inherit lib; };

              users.${user} = {
                imports = [
                  (
                    if false then
                      # This works:
                      #   error: A definition for option `home-manager.users.me.programs.bash.enable' is not of type `boolean'. Definition values:
                      #   - In `/nix/store/rmw0kq593g38kj9dwpg5ka81bbskh9dm-source/flake.nix': "not a bool"
                      { programs.bash.enable = lib.myCustomPrefix.myCustomAttr; }
                    else
                      # This doesn't:
                      #   error: undefined variable 'hm'
                      # That means it's not finding `lib.hm`, the message is not explicit because of `with lib;`.
                      ({ lib, ...}: {
                        programs.bash.enable = lib.myCustomPrefix.myCustomAttr;
                      })
                  )
                ];
              };
            };
          }

          # Required boilerplate for HM to not complain
          # This is not enough to get NixOS to build though, but that doesn't
          # matter for this test: our success condition is "bash.enable is not of type `boolean'".
          {
            home-manager.users.${user}.home.stateVersion = "22.11";

            users.users.${user} = {
              name = user;
              home = "/nonexistent";
            };
          }
        ];
      };
    };
  };
}
```

I managed to make it work by passing `specialArgs = { inherit lib; };` to `lib.nixosSystem` and removing `home-manager.extraSpecialArgs`. I don't understand why though, if you could shed some light that would be greatly appreciated!

<details>
<summary>Full working flake</summary>

You'll still get the "bash.enable is not of type `boolean'" error, but that means the cutom lib extension is working!

```nix
{
  inputs =
  {
    nixpkgs.url = github:NixOS/nixpkgs/7067edc68c035e21780259ed2d26e1f164addaa2;

    home-manager = {
      url = github:ThinkChaos/home-manager/4833c849e3cbc1072e2415e3507671c8c577705e;
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, ... }@inputs:
  let
    lib =  inputs.nixpkgs.lib.extend (self: super: {
      myCustomPrefix = { myCustomAttr = "not a bool"; };
    });

    user = "me";
  in
  {
    nixosConfigurations = {
      test = lib.nixosSystem {
        specialArgs = { inherit lib; };

        system = "x86_64-linux";

        modules = [
          inputs.home-manager.nixosModule {
            home-manager = {
              extraSpecialArgs = {
                # Make sure `lib` is not overriden here!
              };

              users.${user} = {
                imports = [
                  ({ lib, ...}: {
                    programs.bash.enable = lib.myCustomPrefix.myCustomAttr;
                  })
                ];
              };
            };
          }

          # Required boilerplate for HM to not complain
          # This is not enought to get NixOS to build though, but that doesn't
          # matter for this test: our success condition is "bash.enable is not of type `boolean'".
          {
            home-manager.users.${user}.home.stateVersion = "22.11";

            users.users.${user} = {
              name = user;
              home = "/nonexistent";
            };
          }
        ];
      };
    };
  };
}
```
</details>

I also confirmed that with the working version, using HM without the patch proposed in this PR, it fails. Proving the patch now works. Tried with `github:nix-community/home-manager/c8cb60b8a15c90b2bbc416c182532620602edb48`.  
I'll mark this PR as ready.

**Review by ncfavier — APPROVED** [review]

**Comment by zd4y** [comment]
Hello, after commit d82c9af8175878a461a0fdf914e67cc446664570 my configuration no longer works, I get this error:
```
building Nix...
building the system configuration...
error: attribute 'extend' missing

       at /nix/store/drkcqws36icpazfzkkzk4cvwqm4cwd3j-source/modules/lib/stdlib-extended.nix:7:4:

            6| let mkHmLib = import ./.;
            7| in nixpkgsLib.extend (self: super: {
             |    ^
            8|   hm = mkHmLib { lib = self; };
       Did you mean extends?
(use '--show-trace' to show detailed location information)
```

If I change this line:
```nix
home-manager = builtins.fetchTarball "https://github.com/nix-community/home-manager/archive/master.tar.gz";
```
to this line (the version before that commit)
```nix
home-manager = builtins.fetchTarball "https://github.com/nix-community/home-manager/archive/6142193635ecdafb9a231bd7d1880b9b7b210d19.tar.gz";
```
It works.

**Comment by al3xtjames** [comment]
I'm seeing the same thing on x86_64-darwin with `nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-22.11-darwin"`:

```
error: attribute 'extend' missing

       at /nix/store/drkcqws36icpazfzkkzk4cvwqm4cwd3j-source/modules/lib/stdlib-extended.nix:7:4:

            6| let mkHmLib = import ./.;
            7| in nixpkgsLib.extend (self: super: {
             |    ^
            8|   hm = mkHmLib { lib = self; };
       Did you mean extends?

       … while evaluating anonymous lambda

       at /nix/store/drkcqws36icpazfzkkzk4cvwqm4cwd3j-source/modules/lib/stdlib-extended.nix:4:1:

            3|
            4| nixpkgsLib:
             | ^
            5|

       … from call site

       at /nix/store/drkcqws36icpazfzkkzk4cvwqm4cwd3j-source/nixos/common.nix:12:17:

           11|
           12|   extendedLib = import ../modules/lib/stdlib-extended.nix lib;
             |                 ^
           13|

       … while evaluating 'applyModuleArgsIfFunction'

       at /nix/store/p6qg72mllfx16z88l3wwqz8n7ixmqrgr-source/lib/modules.nix:466:39:

          465|
          466|   applyModuleArgsIfFunction = key: f: args@{ config, options, lib, ... }: if isFunction f then
             |                                       ^
          467|     let

       … from call site
```

**Comment by ncfavier** [comment]
Your nixpkgs are too old and don't contain the fix needed to make this work. If you follow the unstable branch of home-manager, you should follow an unstable branch of nixpkgs as well.

**Comment by ThinkChaos** [comment]
Thanks for merging!

**Comment by quentinmit** [comment]
> Your nixpkgs are too old and don't contain the fix needed to make this work. If you follow the unstable branch of home-manager, you should follow an unstable branch of nixpkgs as well.

I also just ran into this; the top-level `README.md` says 

> Home Manager targets [NixOS](https://nixos.org/) unstable and NixOS version 22.11 (the current stable version), it may or may not work on other Linux distributions and NixOS versions.

and it does not work with NixOS 22.11 for me. If master is only targeting unstable, the README should be fixed.

**Comment by mirkolenz** [comment]
I was able to fix this issue by pinning the home-manager version in my flake:

```txt
inputs.home-manager.url = "github:nix-community/home-manager/release-22.11";
```

**Pull request merged**
