### PR TITLE
programs.waybar: remove modules-* from defaults

### PR DESCRIPTION
**Pull request by teto**
I prefer to handle modules-* imperatively for more flexibility, I do this via waybar "includes" (https://github.com/Alexays/Waybar/wiki/Configuration). Current HM defaults modules-* to `[]` instead of null for most other settings, so they get written to ~/.config/waybar/config even though I've configured nothing.

And they take precedence over the impartives ones because of how waybar's includes work:

====
Paths to additional configuration files.
Each file can contain a single object with any of the bar configuration options. In case of duplicate options, the first defined value takes precedence, i.e. including file -> first included file -> etc. Nested includes are permitted, but make sure to avoid circular imports. For a multi-bar config, the include directive affects only current bar configuration object. ====

Since the default is [], they dont bring naything so defaulting to null is a better choice here.

### Checklist

- [ ] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

### CODE REVIEW

**Comment by teto** [comment]
cc @berbiche

**Review by berbiche — APPROVED** [review]
LGTM, but I wonder if this could break anyone's configuration 🤔

**Comment by teto** [comment]
In my short test waybar doesn't enable any modules by default, which is equal to our current default `[]` so I dont think it should break anyone's config. If anything, if they included a manual config like I want, with a `modules-*` defined, their waybar might show modules that were previously ignored by waybar because of our previous default  `[]`.

**Comment by rycee** [comment]
Fair enough, merged to master now.

**Pull request merged**
