### PR TITLE
NixOS: remove indirection via activate-${username}, fixes #2191

### LINKED ISSUE #2191: [discussion] why is the nixos-HM integration via systemd indirected
### Issue description

On NixOS, with HM integrated into a flakes setup as a module, a systemd service is created which runs the home-manager activation script both at boot and when switching the config. After looking a bit into it, in particular to manually reconstruct which nixos generation corresponds to which HM generation, I grepped through the systemd units created for HM activation and discovered that they call an `-activate-` script in the nix store, which basically just contains three lines:
1. `bash -el` hashebang line
2. `echo Activating home-manager configuration for <USER>`
3. `exec /nix/store/<HASH>-home-manager-generation/activate`

I don't really understand why this indirection is there, e.g. why does the systemd script not directly invoke the `...-home-manager-generation/activate` script (esp. because the echo line is pretty redundant given that the systemd service is already named after HM + username, and it even scrolls out of the log displayed by `systemctl status`).

I would propose getting rid of this indirection (e.g. replacing the `ExecStart=` line which currently calls the script directly with the imo appropriate `ExecStart=.../-home-manager-generation/activate`), as it makes keeping track of current HM generations without activating all the present system generations unnecessarily harder, and I can't see any benefit of it (for now; maybe someone can convince me otherwise...).

#### Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.48, NixOS, 21.11.20210716.92b3227 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210715_db4d4cf`
 - nixpkgs: `/etc/nix-flake-channels/nixpkgs`

### PR DESCRIPTION
**Pull request by zseri**
### Description

Fixes #2191.

### Checklist

- [X] Change is backwards compatible.

- [X] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [X] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Review by berbiche — APPROVED** [review]
LGTM!

The script will continue executing when an error occurs now.

**Comment by zseri** [comment]
@berbiche huh, "The script will continue executing when an error occurs now." shouldn't the "set -eu" at the top of the `-.../activate` script prevent this?

**Comment by berbiche** [comment]
> @berbiche huh, "The script will continue executing when an error occurs now." shouldn't the "set -eu" at the top of the `-.../activate` script prevent this?

Thanks. I should have looked at the activation script before responding!

**Comment by berbiche** [comment]
cc @ncfavier #2112.

We could fix both problems at the same time in two separate commits.

**Comment by ncfavier** [comment]
This PR collides with my attempted fix #2147. @berbiche how would you fix it?

**Comment by IvanMalison** [comment]
So when I run this script in a shell I get a bunch of output, but there are never any logs when I look in journalctl. Can anyone explain why that is?

**Comment by IvanMalison** [comment]
> @berbiche huh, "The script will continue executing when an error occurs now." shouldn't the "set -eu" at the top of the `-.../activate` script prevent this?

Interestingly, it appears that this does not have the intended effect though. When I used a home-manager version with this change, the home-manager-(my username) unit appears to succeed, but none of the home-manager services end up linked, and I get this output as part of the unit:

https://gist.github.com/IvanMalison/c39c7eaf152a3a0ff2269a4a8d8e28ef

**Comment by ncfavier** [comment]
> So when I run this script in a shell I get a bunch of output, but there are never any logs when I look in journalctl. Can anyone explain why that is?

Possibly related to https://github.com/systemd/systemd/issues/19751 ? (I came across this while debugging the NixOS module.)

**Comment by zseri** [comment]
> Interestingly, it appears that this does not have the intended effect though. When I used a home-manager version with this change, the home-manager-(my username) unit appears to succeed, but none of the home-manager services end up linked, and I get this output as part of the unit

This appears to be a bug in the activate script...

> Possibly related to systemd/systemd#19751 ? 

I don't think that is related, because (1) the activate script is probably too slow to be affected and (2) the home-manager service isn't run using `systemd --user`, it uses the global systemd.

**Comment by rycee** [comment]
Agreed I think it is some other issue causing that. I tried both a successful and a failing run with the PR changes and it worked as expected for me. So I've merged to master now.

I'll have a look at the other issue that @IvanMalison encountered.

**Pull request merged**
