### PR TITLE
email: add yandex and outlook.office365 email flavor

### PR DESCRIPTION
**Pull request by pleshevskiy**
### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by rycee** [comment]
Thanks! Merged to master now.

**Comment by ambroisie** [comment]
@pleshevskiy [this page](https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-8361e398-8af4-4e97-b147-6c6c4ac95353) seems to indicate `smtp.office365.com` for SMTP.

**Comment by pleshevskiy** [comment]
@ambroisie Thank you. I set up these configurations a long time ago and with a lot of pain. I'll take another look at them tonight.

**Comment by pleshevskiy** [comment]
@ambroisie it works too, thanks! I opened a new PR (https://github.com/nix-community/home-manager/pull/3191)

**Pull request merged**
