### PR TITLE
flake: expose Home Manager lib

### PR DESCRIPTION
**Pull request by kalbasit**
### Description

cherry picked commit 6dc8de259a36313ebd1ee25b075174e396f53329 authored in https://github.com/nix-community/home-manager/pull/1634.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by kalbasit** [comment]
@rycee I don't understand why this is failing :disappointed:

**Comment by berbiche** [comment]
> I don't understand why this is failing :disappointed: 

According to the CI log:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

The CI Actions need updates I think.
Also, enabling dependabot would allow for automatic PRs when Actions are updated.

**Comment by kalbasit** [comment]
@rycee it's green! PTAL.

**Comment by rycee** [comment]
Thanks! Merged now 🙂

**Pull request merged**
