### PR TITLE
sway: stop sway-session.target on exit, reset failed units at startup

### PR DESCRIPTION
**Pull request by 9ary**
### Description

~~There is no reliable way to run cleanup tasks before sway exits, but this ensures that services which depend on graphical-session.target are probably restarted in the next session.~~

This ensures graphical-session.target is properly cycled, and that all of its members are restarted on consecutive runs.

### Checklist

- [x] Change is backwards compatible.

- [ ] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC

@Scrumplex @alexarice @sumnerevans @SebTM @oxalica

### CODE REVIEW

**Comment by oxalica** [comment]
This seems fishy. If you are managing sessions around `sway-session.target` and `graphical-session.target`, they should both be stopped cleanly once you `stop graphical-session.target`, because [`sway-session.target` `BindsTo=graphical-session.target`](https://github.com/oxalica/home-manager/blob/38acf5c610597580082ff320f4bd706f9e2c557a/modules/services/window-managers/i3-sway/sway.nix#L502). Stopping before starting would be a no-op.

> There is no reliable way to run cleanup tasks before sway exits

There is. A typical desktop service, eg. `waybar`, should be and [is already `PartOf=graphical-session.target`](https://github.com/oxalica/home-manager/blob/38acf5c610597580082ff320f4bd706f9e2c557a/modules/programs/waybar.nix#L311), which means they will all be stopped before `graphical-session.target` is stopped. If you want to run new command before exit, `ExecStop` can also do the trick.

**Comment by 9ary** [comment]
The problem is stopping sway-session.target/graphical-session.target when sway exits. Currently, nothing ever does that, so it lingers. The next time you start sway, `systemctl start` is a no-op because the target is already running, so none of the services are actually restarted (eg wlsunset isn't running if I quit sway and restart it).

I suppose an alternative to this would be to put the stop command in the wrapper script.

**Comment by oxalica** [comment]
> The problem is stopping sway-session.target/graphical-session.target when sway exits.

Then let's fix that instead. I'm personally binding the exit shortcut to:
```
systemctl --user stop graphical-session.target; swaymsg exit; loginctl terminate-session $XDG_SESSION_ID'
```
Ideally we should do this whenever sway stops. But currently h-m does not manage sway itself as a systemd service (and this usage is [not supported upstream](https://github.com/swaywm/sway/wiki/Systemd-integration#running-sway-itself-as-a---user-service)). There is a way to monitor sway exit, though https://github.com/swaywm/sway/issues/7128#issuecomment-1206137932.

> I suppose an alternative to this would be to put the stop command in the wrapper script.

That's also a good way to go.

**Comment by 9ary** [comment]
> Ideally we should do this whenever sway stops.

Yeah, this is doable. The only concern I have, which is pretty mild all things considered, is that you can't catch the exit command and delay it until all services have shut down, but that shouldn't be a problem for well-behaved programs.

> There is a way to monitor sway exit, though [swaywm/sway#7128 (comment)](https://github.com/swaywm/sway/issues/7128#issuecomment-1206137932).

IPC also has a shutdown event, but it has the same problem as above so it's pretty useless.

> But currently h-m does not manage sway itself as a systemd service (and this usage is [not supported upstream](https://github.com/swaywm/sway/wiki/Systemd-integration#running-sway-itself-as-a---user-service)).

It shouldn't be anyway. Even gnome, which runs every application as a systemd service, doesn't run the session/compositor as one.

Anyway, doing this in the wrapper seems like the most sensible approach in this case.

**Comment by 9ary** [comment]
Ah right, this is going to be a little annoying. The wrapper `exec`s into sway, so it's not possible to put a trap in extraSessionCommands. Nixpkgs would need to be changed to accommodate us, or we would have to add an extra layer of wrapping.

In this case, the next simplest solution is using swaymsg to wait for sway to exit.

**Review by oxalica — APPROVED** [review]
Works for me. It's kinda weird that the waiting process is under PID 1 rather than sway, but I think the current approach is good enough.

Also the PR title needs a change.

**Comment by 9ary** [comment]
> It's kinda weird that the waiting process is under PID 1 rather than sway

This is because exec double-forks (see https://github.com/swaywm/sway/blob/master/sway/commands/exec_always.c).

> Also the PR title needs a change.

Done.

**Comment by 9ary** [comment]
Rebased.

**Comment by Scrumplex** [comment]
Similar to https://github.com/alebastr/sway-systemd/pull/11, I would propose to also reset failed units. I think some units (like waybar) might fail because they lose their Wayland connection before they would get stopped here

**Comment by 9ary** [comment]
Done. Any idea what's causing the tests to fail? I don't see why that would make a difference...

**Comment by Scrumplex** [comment]
> Done. Any idea what's causing the tests to fail?

The tests compare the final config to a specification. As you have changed the effect of `systemd.enable`, the new final config will not match the previous specification. You will need to adjust `tests/modules/services/window-managers/sway/*.conf`

**Comment by 9ary** [comment]
Thanks, the log was a bit confusing. Hopefully it'll pass now.

**Comment by rycee** [comment]
LGTM but I don't know sway. Ok to merge?

**Review by Scrumplex — APPROVED** [review]
good to go IMO

**Comment by 9ary** [comment]
Rebased. I *think* it's correct, will try it soon (currently working on upgrading to 24.05).

**Comment by rycee** [comment]
Thanks! Merged to master now :slightly_smiling_face:

**Pull request merged**
