### PR TITLE
helix: fix failing test due to file output format change

### PR DESCRIPTION
**Pull request by berbiche**
### Description

Fix the failing Helix test.

### Checklist

- [x] Change is backwards compatible.

- [ ] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by berbiche** [comment]
I will force push this change to the systemd PR.

**Comment by terlar** [comment]
Which is the systemd PR? I think my branch is failing due to these tests:
```
helix-example-settings: FAILED
Expected home-files/.config/helix/config.toml to be same as /nix/store/0ra0cz99dr2kfzzv5rcxr3k7i41dadp3-settings-expected.toml but were different:
--- actual
+++ expected
@@ -1,5 +1,4 @@
 theme = "base16"
-
 [keys.normal.space]
 q = ":q"
 space = "file_picker"
For further reference please introspect /nix/store/mn46ry05dghs30fbsa3nbxrjnr4p49yn-nmt-report-helix-example-settings
```

**Comment by rycee** [comment]
@terlar I made a commit earlier that fixed an error showing up in the CI: https://github.com/nix-community/home-manager/commit/65a32578d9b1394bea5c6336721ec392aadc89fb I assume that some Nixpkgs change has happened recently in the toml rendering.

Perhaps rebasing on top of master will fix the helix error?

**Comment by terlar** [comment]
@rycee Thank you that worked. I must have just missed the commit during my rebase, I rebased again and now everything is working.

**Pull request closed without merging**
