### PR TITLE
pam: add yubico option

### PR DESCRIPTION
**Pull request by veehaitch**
### Description

Write YubiKey token IDs in the format yubico_pam expects. See
https://developers.yubico.com/yubico-pam/ for details. Also refer to the
NixOS option [`security.pam.services.<name>.yubicoAuth`](https://search.nixos.org/options?channel=21.05&show=security.pam.services.%3Cname%3E.yubicoAuth&from=0&size=100&sort=relevance&type=packages&query=security.pam.services+yubicoAuth).

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Review by berbiche — COMMENTED** [review]
Cool! Thanks for the PR.

Do you think it would also be possible to add an option to configure u2f keys for yubico's PAM u2f module?

The u2f keys are written to `$XDG_CONFIG_HOME/Yubico/u2f_keys` in the following format: `<username>:<KeyHandle1>,<UserKey1>,<CoseType1>,<Options1>:<KeyHandle2>,<UserKey2>,<CoseType2>,<Options2>:...`. New keys are appended with another colon `:`.

**Comment by veehaitch** [comment]
> Do you think it would also be possible to add an option to configure u2f keys for yubico's PAM u2f module?

Sure, that's certainly possible! However, I'd suggest to do it in another PR if that works for you 🙂

**Comment by veehaitch** [comment]
Anything left I can do to get this PR merged? @rycee

**Comment by rycee** [comment]
Thanks! Rebased to master in d8f9dcfbd34bace6da54462f2ea08e0f19e21378.

**Pull request closed without merging**
