### PR TITLE
README.md: remove alpha disclaimer

### PR DESCRIPTION
**Pull request by Mic92**
I think home-manager matured enough and has enough user that big breakages are not likely/will be fixed quickly

### CODE REVIEW

**Comment by rycee** [comment]
I agree that HM is mature enough that it is unlikely to cause any major technical problems for anybody. But I'd like to keep the disclaimer to moderate popularity and the expectation of polish. Mainly I'm worried that HM will get too many users too quickly to cope with the associated influx of PRs and issues. Unfortunately I'm already mostly ignoring non-PR issues unless they are of a critical nature.

**Comment by Mic92** [comment]
> I agree that HM is mature enough that it is unlikely to cause any major technical problems for anybody. But I'd like to keep the disclaimer to moderate popularity and the expectation of polish. Mainly I'm worried that HM will get too many users too quickly to cope with the associated influx of PRs and issues. Unfortunately I'm already forced to mostly ignore non-PR issues unless they are of a critical nature.

Is it maybe time to move this to the NixOS org or nix-community so that the maintainer team can be scaled as well? It can be a lot of maintenance burden to keep track of everything for one person.

**Comment by rycee** [comment]
Yeah, moving to the NixOS organization was briefly discussed in https://discourse.nixos.org/t/why-isnt-more-of-home-manager-merged-into-nixpkgs/6096 but I think nothing concrete came out of it.

**Comment by Mic92** [comment]
> Yeah, moving to the NixOS organization was briefly discussed in [discourse.nixos.org/t/why-isnt-more-of-home-manager-merged-into-nixpkgs/6096](https://discourse.nixos.org/t/why-isnt-more-of-home-manager-merged-into-nixpkgs/6096) but I think nothing concrete came out of it.

Well. Make an RFC to move home-manager to the NixOS org I suppose.

**Comment by rycee** [comment]
Yeah, an RFC or something similar might be a good idea and I would welcome anybody who'd like to take lead on writing one. Unfortunately I don't have the time and motivation to do it myself.

**Comment by teto** [comment]
can't we just move it to nix-community ? RFC seems a bit heavyweight. Alternatively we could set clearer boundaries on what code gets accepted/refused. With flakes, we may also be able to let other repositories provide their own HM modules ?

**Comment by Mic92** [comment]
I have sent an invite to rycee. After acceptance the repo can be moved to nix-community.

**Comment by rycee** [comment]
Ah, cool. I tried switching it over. Dunno if it worked.

**Comment by teto** [comment]
it worked :)

**Comment by Mic92** [comment]
I also added an issue for boarding new maintainer: https://github.com/nix-community/home-manager/issues/1481 @rycee if you know people you want to add, just add them there.

**Comment by teto** [comment]
The project doesn't have the kind of support nixos or nixpkgs has so I understand if rycee doesn't want to remove that disclaimer. Shall we close this ? The stars number is a good indicator that it mostly works regardless of the disclaimer.

**Pull request closed without merging**
