### PR TITLE
version: allow 25.05 as state version

### PR DESCRIPTION
**Pull request by oneingan**
nixpkgs updated upstream: https://github.com/NixOS/nixpkgs/commit/90fcf3aa7eba70f18dad15b634e9336b997d25ac

### CODE REVIEW

**Comment by rycee** [comment]
Thanks! Merged to master now 🙂

**Comment by i-am-logger** [comment]
not sure this is complete... I still get the warning home is running on 24.05 even though `home.stateVerson = "25.05";`

image

**Comment by i-am-logger** [comment]
might be the `release.json` needs an update?

https://github.com/nix-community/home-manager/blob/5056a1cf0ce7c2a08ab50713b6c4af77975f6111/release.json#L2

**Comment by muradbu** [comment]
> not sure this is complete... I still get the warning home is running on 24.05 even though `home.stateVerson = "25.05";`
> 
> image

I'm running into the same issue currently

**Comment by oneingan** [comment]
This change is the minimal required to avoid evaluation errors with the latest nixpkgs. If you want to proceed, you can use the home.enableNixpkgsReleaseCheck = false; option as suggested.

I assume that bumping home-manager requires a stricter release process than just a simple string change.

**Comment by i-am-logger** [comment]
> This change is the minimal required to avoid evaluation errors with the latest nixpkgs. If you want to proceed, you can use the home.enableNixpkgsReleaseCheck = false; option as suggested.
> 
> I assume that bumping home-manager requires a stricter release process than just a simple string change.

i am not sure what is the release process for home-manager and what is required to change the `release.json` 

More work is required to properly release a 25.05 home-manager

**Pull request merged**
