### PR TITLE
go-2fa: add module

### PR DESCRIPTION
**Pull request by mlvzk**
### Description

This PR adds a go-2fa program module.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/rycee/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

This is a pretty small module, are test cases required?

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/rycee/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/rycee/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/rycee/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [x] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by rycee** [comment]
Thanks for the contribution! I'm a bit reluctant to merge this, though, since the codes will kept in plain text and world-readable in the Nix store. See, e.g., https://github.com/NixOS/nix/issues/8 for previous discussions about improving the "secrets in Nix" story.

**Comment by mlvzk** [comment]
@rycee Would it be enough to put a warning in the description of `codes`? Like in this PR https://github.com/NixOS/nixpkgs/pull/33890/commits/22e83d26673160bc7ad6f5a36b9ee01373806cd8

**Comment by mlvzk** [comment]
> @rycee Would it be enough to put a warning in the description of `codes`? Like in this PR [NixOS/nixpkgs@22e83d2](https://github.com/NixOS/nixpkgs/commit/22e83d26673160bc7ad6f5a36b9ee01373806cd8)

 @rycee could you reply?

**Comment by eyJhb** [comment]
@mlvzk you could make it read them from a file instead, so that they do not come into the Nix store

**Pull request closed without merging**
