### PR TITLE
programs.neovim: dont create init.vim if empty

### PR DESCRIPTION
**Pull request by teto**
dont wraprc

### Checklist

@DanCardin can you confirm ?

- [ ] Change is backwards compatible.

- [ ] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Review by fricklerhandwerk — APPROVED** [review]

**Review by Congee — APPROVED** [review]

**Review by sumnerevans — APPROVED** [review]

**Comment by teto** [comment]
Questions: do the approval mean you've tested it ?

**Comment by Congee** [comment]
@teto I just tested this PR with this channel `https://github.com/teto/home-manager/archive/neovim-nowrap.tar.gz`

The only config I have is
```nix
programs.neovim.enable = true;
```
But, `$XDG_CONFIG_HOME/nvim/init.vim` is still linked to a file `/nix/store/rwgwkflpblp8a45l4hi6mya0vv6zypv5-hm_nviminit.vim` containing
```vim
" configuration generated by NIX
set nocompatible

set packpath^=/nix/store/dwhxn7sd81352p8fbb98a8rw9qwbb8ns-vim-pack-dir
set runtimepath^=/nix/store/dwhxn7sd81352p8fbb98a8rw9qwbb8ns-vim-pack-dir
```

**Comment by teto** [comment]
what nixpkgs are you on ? The test passes `neovim-no-init: OK` so I tend to think you are doing sthg wrong.

**Comment by Congee** [comment]
> what nixpkgs are you on ? The test passes `neovim-no-init: OK` so I tend to think you are doing sthg wrong.

https://nixos.org/channels/nixpkgs-unstable

How am I supposed to debug "doing sth wrong"?

**Comment by sumnerevans** [comment]
> Question: do the approval mean you've tested it ?

No, I haven't tested. I looked at the test case and it looks right. I can test later if you would like.

**Comment by berbiche** [comment]
> > what nixpkgs are you on ? The test passes `neovim-no-init: OK` so I tend to think you are doing sthg wrong.
> 
> https://nixos.org/channels/nixpkgs-unstable
> 
> How am I supposed to debug "doing sth wrong"?

The nixpkgs-unstable channel hasn't moved in 5 days according to <https://status.nixos.org>.
I suppose @teto recently merged a change in nixpkgs that hasn't made it into the channel yet.

**Comment by teto** [comment]
@Congee try to check the differences with the CI : CI tests are run against nixos-unstable which according to https://status.nixos.org/ is more recent than nixpkgs-unstable and should thus contain the code you are missing. It's a rare case where nixos-unstable is in advance over nixpkgs-update :s

**Comment by Congee** [comment]
> @Congee try to check the differences with the CI : CI tests are run against nixos-unstable which according to https://status.nixos.org/ is more recent than nixpkgs-unstable and should thus contain the code you are missing. It's a rare case where nixos-unstable is in advance over nixpkgs-update :s

Thank you for the pointer ;) Just tried with nixos-unstable, still the same error.

**Comment by teto** [comment]
@Congee so I've just tested it and I apologize it seems like you are right, the init.vim is created because the RC setups packpath towards an empty folder. I was using `assertPathNotExists` wrong, passing the absolute path when a relative one is enough:
```
function assertPathNotExists() {
    if [[ -e "$TESTED/$1" ]]; then
        fail "Expected $1 to be missing but it exists."
    fi
```
I've rebased the branch but seems like we have a new issue with nixos-unstable. Will fix later today.

**Comment by teto** [comment]
I've disabled the failing test, I will reenable it when https://github.com/NixOS/nixpkgs/pull/125547 gets into unstable.
This PR fixes some issues like duplicated init + it also stops the wrapping of init.vim, as was done one / two weeks ago.

**Pull request merged**
