### PR TITLE
mullvad-browser: initial support

### PR DESCRIPTION
**Pull request by heywoodlh**
### Description

Initial support for configuring Mullvad Browser.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Additional Info

I tested my fork and the Mullvad Browser seems to be configured properly on both Linux and MacOS! :smile:

I'm not sure if the tests I added will work. Since Mullvad Browser is just a copy of Firefox, I tried to copy Firefox and modify the tests in a way that made sense. I could use some help on that. I did run the tests on Linux and I didn't seem to have issues -- but, again, I could use help on the tests.

### CODE REVIEW

**Comment by brckd** [comment]
i tried to use the module and it seems like you forgot to import it in `modules/modules.nix` and add the package to `home.packages`

**Comment by heywoodlh** [comment]
@brckd I believe I added the necessary changes, could you test again and let me know?

**Comment by brckd** [comment]
for some reason i get [this error](https://l.termbin.com/mfss) when trying to `config.programs.mullvad-browser.enable = true`

**Comment by heywoodlh** [comment]
With https://github.com/nix-community/home-manager/pull/5128 merged I'm going to close this as it's likely unnecessary at this point since Mullvad Browser is a Firefox derivative.

**Pull request closed without merging**
