### PR TITLE
xsession.pointerCursor: .icons file for AwesomeWM

### LINKED ISSUE #2081: Xcursor module not follow XDG specification
### Issue description

I believe this module should be creating the file in ".icons/default/index.theme", according to https://wiki.archlinux.org/title/Cursor_themes#XDG_specification, just like lxappearance does. 
Without this file my AwesomeWM will not use the cursor theme.

#### Maintainer CC

@rycee 

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.7, NixOS, 21.11pre293730.1ca6b0a0cc3 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.11pre293730.1ca6b0a0cc3, home-manager, nixpkgs-21.03pre249813.26d3fbf2156"`
 - channels(seraphybr): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by league**
closes #2081

### Description

Writes the file `~/.icons/default/index.theme`, which allows AwesomeWM (perhaps others?) to use the pointerCursor setting.

### Checklist

- [x] Change is backwards compatible. **(Unless a user is writing that file from their own config.)**

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef). **(There isn't a test case for this module yet.)**

- [x] Commit messages are formatted like **(I didn't use a long description, but referenced the reported issue instead)**

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR ~~adds a new module~~

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Review by berbiche — APPROVED** [review]
LGTM!

Seems harmless.

**Comment by lovesegfault** [comment]
This broke my setup as I now get this
```
error: builder for '/nix/store/vbfgzglpq417kvkhs12ibz7778s4mjrl-home-manager-files.drv' failed with exit code 1;
       last 1 log lines:
       > Error installing file '.icons/default/index.theme' outside $HOME
```

Unclear to me why though.

**Comment by berbiche** [comment]
> This broke my setup as I now get this
> ```
> error: builder for '/nix/store/vbfgzglpq417kvkhs12ibz7778s4mjrl-home-manager-files.drv' failed with exit code 1;
>        last 1 log lines:
>        > Error installing file '.icons/default/index.theme' outside $HOME
> ```
> 
> Unclear to me why though.

Is it possible your folder .icons is a symlink to a folder outside home?

**Comment by lovesegfault** [comment]
> > This broke my setup as I now get this
> > ```
> > error: builder for '/nix/store/vbfgzglpq417kvkhs12ibz7778s4mjrl-home-manager-files.drv' failed with exit code 1;
> >        last 1 log lines:
> >        > Error installing file '.icons/default/index.theme' outside $HOME
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Unclear to me why though.
> 
> Is it possible your folder .icons is a symlink to a folder outside home?

As far as I can tell `.icons` is being generated by `home-manager`

```
❯ ls $HOME/.icons
Permissions Size User     Date Modified Name
lrwxrwxrwx    77 bemeurer  9 Jun 22:46  default -> /nix/store/mg4hkybs1qijhapy12nqm6sgn70jf40z-home-manager-files/.icons/default/
```

**Comment by league** [comment]
Interesting… I didn't see anywhere in the current home-manager source that `home.file.".icons/…"` was being set. So it would help to figure out where this comes from.

It looks like `.icons/default/` is indeed a directory, but the conflicting module is linking the whole directory rather than individual files which would make it (more likely) possible to merge them. What's in the directory – is it also `index.theme` or other files?

**Comment by lovesegfault** [comment]
```
❯ tree $HOME/.icons
/home/bemeurer/.icons
└── default -> /nix/store/mg4hkybs1qijhapy12nqm6sgn70jf40z-home-manager-files/.icons/default
```

```
❯ tree -L 1 /nix/store/mg4hkybs1qijhapy12nqm6sgn70jf40z-home-manager-files/.icons/default
/nix/store/mg4hkybs1qijhapy12nqm6sgn70jf40z-home-manager-files/.icons/default
├── 16x16
├── 22x22
├── 24x24
├── 256x256
├── 32x32
├── 48x48
├── 512x512
├── 64x64
├── 8x8
├── 96x96
├── cursors
├── icon-theme.cache
├── index.theme
├── scalable
└── scalable-up-to-32
```

**Comment by berbiche** [comment]
I'll open a PR reverting this in the meantime.

**Comment by lovesegfault** [comment]
This is still failing for me, I'll make a reversal PR :)

**Pull request merged**
