### PR TITLE
firefox: fix policies availability

### PR DESCRIPTION
**Pull request by brckd**
### Description

Fixes https://github.com/nix-community/home-manager/pull/5128#discussion_r1727796541. Alltho this hasn't created any issues yet, it makes more sense semantically.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC

@rycee @kira-bruneau @brckd

### CODE REVIEW

**Comment by timon-schelling** [comment]
> Fixes [#5128 (comment)](https://github.com/nix-community/home-manager/pull/5128#discussion_r1727796541). Alltho this hasn't created any issues yet, it makes more sense semantically.

Would become a issue when only providing a unwrapped package to the function. Like I did :)

**Comment by rycee** [comment]
Unfortunately, as the CI suggests this won't work. Since `isWrapped` is defined

```nix
isWrapped = versionAtLeast config.home.stateVersion "19.09"
  && wrappedPackageName != null;
```

it depends on the evaluated configuration. So this would introduce a dependency between the option definitions and the final configuration.

Perhaps it is sufficient to have

``` nix
policies = optionalAttrs (wrappedPackageName != null) (mkOption { … });

**Comment by brckd** [comment]
Thanks for the comment! I found the CI error hard to understand and didn't know if it was caused by me. I will add the suggested fix tomorrow. As far as I know, the version check was added for backwards compatibility with previous HM versions of FF, so it might be redundant in the generic module anyways.

**Comment by rycee** [comment]
Thanks! CI was happier this time so I've merged to master now 🙂

**Comment by nyabinary** [comment]
Hmm, I have an issue. I don't know if it's my side though when I switched from `chaotic-nyx` firefox-nightly to `nix-community` firefox-nightly flake all the policies are not being applied that I set but all the other things I set (not a part of policies) *are* being applied. I tried nuking my whole profile and Mozilla and cache folder to no avail, policies still not being set.

**Comment by brckd** [comment]
> Hmm, I have an issue. I don't know if it's my side though when I switched from `chaotic-nyx` firefox-nightly to `nix-community` firefox-nightly flake all the policies are not being applied that I set but all the other things I set (not a part of policies) _are_ being applied. I tried nuking my whole profile and Mozilla and cache folder to no avail, policies still not being set.

@nyabinary Seems like you are experiencing #5278. As its first comment points out, policies aren't applied because the nightly package is unwrapped. The suggested solution https://github.com/nix-community/home-manager/issues/5278#issuecomment-2113253777 seems to involve chaotic-nyx's `wrapFirefox`.

**Comment by nyabinary** [comment]
> > Hmm, I have an issue. I don't know if it's my side though when I switched from `chaotic-nyx` firefox-nightly to `nix-community` firefox-nightly flake all the policies are not being applied that I set but all the other things I set (not a part of policies) _are_ being applied. I tried nuking my whole profile and Mozilla and cache folder to no avail, policies still not being set.
> 
> @nyabinary Seems like you are experiencing #5278. As its first comment points out, policies aren't applied because the nightly package is unwrapped. The suggested solution [#5278 (comment)](https://github.com/nix-community/home-manager/issues/5278#issuecomment-2113253777) seems to involve chaotic-nyx's `wrapFirefox`.

Hmm, is this something HM can fix or is it on the user side?

**Comment by brckd** [comment]
> > > Hmm, I have an issue. I don't know if it's my side though when I switched from `chaotic-nyx` firefox-nightly to `nix-community` firefox-nightly flake all the policies are not being applied that I set but all the other things I set (not a part of policies) _are_ being applied. I tried nuking my whole profile and Mozilla and cache folder to no avail, policies still not being set.
> > 
> > @nyabinary Seems like you are experiencing #5278. As its first comment points out, policies aren't applied because the nightly package is unwrapped. The suggested solution [#5278 (comment)](https://github.com/nix-community/home-manager/issues/5278#issuecomment-2113253777) seems to involve chaotic-nyx's `wrapFirefox`.
> 
> Hmm, is this something HM can fix or is it on the user side?

Sorry for the late reply. It's possible to create a `firefox-nightly` module for home manager. But I think it's unlikely as long as it would depend on chaotic nyx. For the time being, the user will have to deal with it, but feel free to contribute a solution for home manager.

**Pull request merged**
