### PR TITLE
redshift/gammastep: Unify common options

### PR DESCRIPTION
**Pull request by thiagokokada**
### Description

Nowadays `services.{redshift,gammastep}` modules are really similar. They should, since Gammastep is a fork of Redshift with the main objective is to support Wayland.

So instead of trying to maintain two separate modules, this commit unify the options in lib/options.nix file, while the implementation of the module itself ends up being really simple (just calling the common options with the necessary parameters to differentiate between them).

My reasoning for this is to make maintaining the modules easier, but also I want to update the modules to use [config file](https://github.com/jonls/redshift/blob/master/redshift.conf.sample) instead of passing parameters via command-line, since this will allow it to support options not supported currently. Modifying both modules separately would be very error prone, so I decided to first unify them and afterwards I can open another PR migrating them to the config file.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [x] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by thiagokokada** [comment]
Did some improvements in tests so we make sure that this commit is not breaking anything.

**Comment by thiagokokada** [comment]
CC @rycee @petabyteboy .

**Comment by rycee** [comment]
Thanks! Merged to master.

I suspect that if gammastep supports both X and Wayland then we may want to consider removing the redshift module entirely but perhaps it's best to wait a while to see how the two projects develop.

In any case, thanks for the contribution!

**Comment by thiagokokada** [comment]
> I suspect that if gammastep supports both X and Wayland then we may want to consider removing the redshift module entirely but perhaps it's best to wait a while to see how the two projects develop.

`redshift` seems to be focusing in having a `dbus` integration nowadays: https://github.com/jonls/redshift/pull/54. `gammastep` itself doesn't seem to have much interested on it: https://gitlab.com/chinstrap/gammastep/-/issues/11. So yeah, the projects can diverge in the future, and some people may prefer to use one (for example, redshift for dbus support) or another (gammastep for wayland support).

**Pull request merged**
