### PR TITLE
fix/generic linux nix

### LINKED ISSUE #2848: bug: bin/home-manager-generation fails due to conflicts with prior installed nix profile entries
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Building `activationPackage` and calling `bin/home-manager-generation` produces an error about conflicting packages in the user environment managed via `nix profile`. The conflicting package comes from a prior invocation of some `bin/home-manager-generation` produced by the same version of home-manager.

`nix profile list` output:
```
0 - - /nix/store/cixwgxv2fsibh4gp183nkqk3w7yhac59-home-manager-path
```

`bin/home-manager-generation` output (after removing one entry from `home.packages`):
```
Starting Home Manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
error: packages '/nix/store/hf1zyw9rpc2vwsljyyvx0k2g7cilaaqc-home-manager-path/opt/teams/locales/am.pak' and '/nix/store/7il2bcjnh2zksfsi67ad7rdqisb4cird-teams-1.4.00.26453/opt/teams/locales/am.pak' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)

Oops, Nix failed to install your new Home Manager profile!

Perhaps there is a conflict with a package that was installed using
"nix profile install"? Try running

    nix profile list

and if there is a conflicting package you can remove it with

    nix profile remove {number | store path}

Then try activating your Home Manager configuration again.
```

### Maintainer CC

@rycee
@blaggacao 
@FlorianFranzen 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.29, NixOS, 22.05 (Quokka), 22.05.20220323.1d08ea2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixos-21.05.2693.d5aadbefd65, nixos-20.09-20.09.4393.068984c00e0"`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`
```
```

### PR DESCRIPTION
**Pull request by blaggacao**
- fix: use the correct nix under generic linux conditions

### CODE REVIEW

**Comment by rycee** [comment]
I'm a bit worried that `config.nix.package` can be `null` and then will cause an error. I'm guessing that there needs to be a `null` check and the PATH `nix` should be used when the test fails. See https://github.com/nix-community/home-manager/blob/423211401c245934db5052e3867cac704f658544/modules/misc/nix.nix#L92-L99

**Comment by blaggacao** [comment]
Git ya, both darwin and nixos can be more confident about its presence?

**Comment by rycee** [comment]
Actually, neither the nixos or nix-darwin modules sets the HM `nix.package` option. I'm not certain whether they should, will have to think about it for a while.

In any case, merged this PR to master now. Thanks for the fix! 🙂

**Comment by blaggacao** [comment]
It makes sense to avoid having different versions of nic in the closure.

I have two different nixpkgs levels and set the option. Consequently I ended up with two versions of nix in the closure (nix2.11 & nix2.4).

**Pull request merged**
