### PR TITLE
programs.neovim: use new nixpkgs API

### PR DESCRIPTION
**Pull request by teto**
### Description

attempt to fix https://github.com/nix-community/home-manager/issues/1907 once https://github.com/NixOS/nixpkgs/pull/120445 is merged.

### Checklist

- [ ] Change is backwards compatible.

- [ ] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by teto** [comment]
The merge of https://github.com/NixOS/nixpkgs/pull/120445 may be problematic for home-manager as it wraps the init.vim by default. `, wrapRc ? true` should be set to false. I will fix it once home-manager bumps to a nixpkgs version with that breaking change.

**Comment by teto** [comment]
The PR shows where to use the `wrapRc = false;` that is needed for nixos-unstable-small. I still need to check the init.vim is not created when config is empty.

**Comment by yourfavouriteuncle** [comment]
I'm hitting this problem right now, rc is not generated / found

**Comment by teto** [comment]
should be ok on nixpkgs master+ hm master.

**Comment by berbiche** [comment]
@teto sorry I don't track all the neovim changes between nixpkgs and here.
What's the status on this PR?
Are you waiting for a review before merging?

**Comment by sumnerevans** [comment]
@teto looks like #120445 has hit nixpkgs-unstable and nixos-unstable: http://nixpk.gs/pr-tracker.html?pr=120445

Users are having issues after upgrading to 21.05, and I think this is the cause.

**Comment by teto** [comment]
@berbiche no problem this ended up being a bit confusing as the changes impacted several aspects. I anm trying to have nixpkgs mimic home-manager interface when dealing with plugin configuration. This PR is intended to remove some code of home-manager once it will have reached nixpkgs. Converted back to draft meanwhile

**Comment by luisfelipemourapereira** [comment]
One workaround to this is...

```
programs.zsh.shellAliases = {
  vim = "nvim -u ~/.config/nvim/init.lua"
};
```

the alias will run neovim with the lua file directly and ignore the init.vim created by nix

**Comment by teto** [comment]
becareful when using `-u`, it inhibits certain behaviors like `exrc` for instance

**Pull request closed without merging**
