### PR TITLE
bash: add bash-completion

### PR DESCRIPTION
**Pull request by maximsmol**
### Description

Add `bash-completion` support to the bash module, similar to the [NixOS module](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/bash/bash-completion.nix). Solves #1464 + related to #191

Note sure what to do about tests with this one since it does not seem we currently test `.bashrc` (`initExtra`) in any way but will add one if needed

Note: sorry for the awful diff, the file was not formatted correctly on master so `nixfmt` messed it up

### Checklist

- [X] Change is backwards compatible.

- [X] Code formatted with `./format`.

- [X] Code tested through `nix-shell --pure tests -A run.all`.

- [X] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [X] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [X] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [X] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by maximsmol** [comment]
By the way, this makes a lot of the packages' bash completion work out of the box without any extra integration steps. So a lot of the `enableBashIntegration` options become kind of useless?

This also seems to already be the case for Zsh since it [also adds the nix profile paths to `fpath`?](https://github.com/nix-community/home-manager/blob/master/modules/programs/zsh.nix#L472-L474)

**Comment by rycee** [comment]
Thanks for the contribution! I think most people enable bash completion option through the NixOS option. Will this change work OK with that? For example, will it enable bash completion twice?

Also, could you restore the formatting of the file? The Bash module is intentionally not formatted through nixfmt. You can use the `format` script in the project root to do code formatting and it will omit the excluded files.

**Comment by wmertens** [comment]
this seems useful but indeed it would cause the completions to load twice.

However, the bash completion script itself sets `BASH_COMPLETION_VERSINFO=(2 11)`, so if that is set, the bash completion could be skipped?

@rycee out of interest, why is this file not autoformatted? Would `nixpkgsfmt` perform better?

**Comment by rycee** [comment]
The `news.nix` file is not auto formatted since it would cause merge conflicts in various PRs. At some point the formatting exception should be removed.

I think the `enableXyzIntegration` options are best to be considered for things like starship and mcfly, i.e., more invasive shell integrations. Plain shell completions for installed tools should, in my opinion, always be installed by the Nixpkgs package and used automatically with no option to disable them.

Checking for `BASH_COMPLETION_VERSINFO` and making the sourcing conditional on that seems like a decent compromise.

**Comment by jameysharp** [comment]
Disclaimer: I just started using home-manager this week and haven't looked closely at how programmable completion works before.

That said: it looks to me like you don't need to source anything from `/share/bash-completion/completions/`. The `bash_completion` script itself does so as-needed for every path in `$XDG_DATA_DIRS`, and it looks like something already adds the `share` subdir to that from each path in `$NIX_PROFILES`.

I'd love to see this merged; I was quite surprised, on trying out home-manager for the first time, to not get completions for man pages. I have a new machine where I have to use Ubuntu after years with NixOS, and I'm hoping to get some of the NixOS feel back using home-manager.

**Comment by rycee** [comment]
Created #3131 with an alternative implementation, which deprecates this one.

**Pull request closed without merging**
