### PR TITLE
flake.nix: get rid of flake-utils

### LINKED ISSUE #3859: Can flake-utils be removed/inlined?
I dislike needing to add tools to the dependency tree and lockfile when mostly all this is doing is calling `forEach` which can be done with built-ins. The escape function could be inlined as well and by doing this there would not be external dependencies.

### PR DESCRIPTION
**Pull request by AndersonTorres**
### Description

Not the smartest removal: it just copy-pastes the code from flake-utils.

Closes #3859 (hopefully)

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by ncfavier** [comment]
*Why??*

**Comment by AndersonTorres** [comment]
> _Why??_

I have linked the [issue](https://github.com/nix-community/home-manager/issues/3859).

Given that it uses only one function from flake-utils, it does make sense to me.

**Comment by zimbatm** [comment]
Instead of copy-pasting flake-utils, create your own "forAllSystems" like this: https://github.com/NixOS/nixpkgs/blob/953b44aaeabf59aaa113db862f82db346f540c02/flake.nix#L14
and then use it on all the outputted attributes. It's going to be a lot less LOC.

**Comment by AndersonTorres** [comment]
This is why I put this on draft. I am not cogitating to merge in this current state.

**Comment by rycee** [comment]
Perhaps something like

```patch
diff --git a/flake.nix b/flake.nix
index 496206c3..3cb02d32 100644
--- a/flake.nix
+++ b/flake.nix
@@ -2,9 +2,8 @@
   description = "Home Manager for Nix";
 
   inputs.nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
-  inputs.utils.url = "github:numtide/flake-utils";
 
-  outputs = { self, nixpkgs, utils, ... }:
+  outputs = { self, nixpkgs, ... }:
     {
       nixosModules = rec {
         home-manager = import ./nixos;
@@ -84,23 +83,29 @@
             };
           });
       };
-    } // utils.lib.eachDefaultSystem (system:
-      let
-        pkgs = nixpkgs.legacyPackages.${system};
-        docs = import ./docs { inherit pkgs; };
-        tests = import ./tests { inherit pkgs; };
-        hmPkg = pkgs.callPackage ./home-manager { };
-      in {
-        devShells.tests = tests.run;
-        packages = {
+    } // (let
+      forAllSystems = nixpkgs.lib.genAttrs nixpkgs.lib.systems.flakeExposed;
+    in {
+      devShells = forAllSystems (system:
+        let
+          pkgs = nixpkgs.legacyPackages.${system};
+          tests = import ./tests { inherit pkgs; };
+        in tests.run);
+
+      packages = forAllSystems (system:
+        let
+          pkgs = nixpkgs.legacyPackages.${system};
+          docs = import ./docs { inherit pkgs; };
+          hmPkg = pkgs.callPackage ./home-manager { };
+        in {
           default = hmPkg;
           home-manager = hmPkg;
 
           docs-html = docs.manual.html;
           docs-json = docs.options.json;
           docs-manpages = docs.manPages;
-        };
-        # deprecated in Nix 2.7
-        defaultPackage = self.packages.${system}.default;
-      });
+        });
+
+      defaultPackage = forAllSystems (system: self.packages.${system}.default);
+    });
 }
```
?

**Comment by rycee** [comment]
Thanks! Merged to master now 🙂

**Pull request merged**
