### PR TITLE
firefox: organize tests by submodule

### PR DESCRIPTION
**Pull request by kira-bruneau**
### Description

Split off from #5697, organizes firefox tests by submodule.

This is intended to match directory structure setup for the new search submodule.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC

@rycee @brckd

### CODE REVIEW

**Review by brckd — APPROVED** [review]
Thank you! This doesn't seem to create merge conflicts as of yet.

Just note that `firefox/firefox.nix` was named like that so that other derivatives could be added to e.g. `firefox/librewolf.nix`. Changing it to `firefox/default.nix` suggests to add tests for other derivatives to e.g. `librewolf/default.nix`. I'm indifferent to this change.

**Comment by kira-bruneau** [comment]
Oh ok sorry! I didn't realize that was a recent change. I just noticed it seemed out of place compared to all the other tests. I'll change it back.

**Review by brckd — APPROVED** [review]

**Comment by kira-bruneau** [comment]
Tests are currently failing on macos-latest due to: https://github.com/NixOS/nixpkgs/issues/345965

**Comment by kira-bruneau** [comment]
I tried rebasing in fe98bae45219dc319b8c6f32a7bb07da1e15ce4f to fix the macos-latest tests, but it failed again for another reason: https://github.com/NixOS/nixpkgs/issues/345965

... but then I pushed 681e84890a4e3fcadc8673cdb9abd1d40e53a70f and it's now passing.

**Comment by teto** [comment]
I am oblivious to the change but firefox maintainer approves so lets' merge

**Pull request merged**
