### PR TITLE
jujutsu: support darwin guidelines for config placement

### PR DESCRIPTION
**Pull request by jkachmar**
### Description

backports changes from https://github.com/nix-community/home-manager/pull/5416 to the `release-24.05` branch.

#### Maintainer CC

@shikanime

### CODE REVIEW

**Review by shikanime — APPROVED** [review]

**Comment by jkachmar** [comment]
how does merging work for `home-manager` anyway? @rycee merged the original PR, but the UI says we should be able to merge this with an approval from a maintainer.

**Comment by rycee** [comment]
Thanks! Rebased to the 24.05 branch in 3288b74c61b9cc09dd2d10854f5876b10d9f9383.

**Comment by puppe** [comment]
I appreciate this change in the grand scheme of things. With jj ignoring XDG_CONFIG_HOME, this is definitely the right thing to do. But as I already had a workaround in place by setting JJ_CONFIG, this just broke my setup. It took me embarassingly long to find the cause  (in part because I had forgotten about setting JJ_CONFIG).

Personally, I would have preferred if this would not have been backported. If this had come with the next release with an accompanying entry in the release notes, that would probably have saved me a lot of time. (I hope I do not sound too cranky. It is getting late in UTC+0200.)

**Comment by rycee** [comment]
@puppe Sorry about the wasted time! I think you have a good point about this being a breaking change and it shouldn't have made it into the stable branch.

Maybe it still would have been valuable to bring into the stable branch but perhaps with a news entry conditioned on jujutsu being enabled, then you at least would be notified about the change.

In any case, I will keep this in mind for the future.

**Pull request closed without merging**
