### PR TITLE
rofi: fix theme definition in configuration for 1.7.0+

### PR DESCRIPTION
**Pull request by lilyinstarlight**
### Description

Since Rofi 1.7.1 (specifically davatorium/rofi@0e70d8a), the deprecated `theme` option in the `configuration` section no longer works and throws an error. For 1.7.0 and up (see https://github.com/davatorium/rofi/releases/tag/1.7.0), `@theme "name"` is supposed to be used and must be after the `configuration` section

This PR updates the config generation for this and specifically makes sure `@theme` goes last

Module maintainer: @thiagokokada 

### Checklist

- [x] Change is backwards compatible. (Rofi 1.7.0+ which is only in unstable channel)

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by thiagokokada** [comment]
LGTM.

**Review by thiagokokada — APPROVED** [review]

**Review by berbiche — APPROVED** [review]
Thanks!

LGTM.

**Comment by ncfavier** [comment]
This could use a backport to the 21.11 branch (see https://discourse.nixos.org/t/trouble-configuring-rofi-theme-in-home-nix/16641)

**Comment by rycee** [comment]
Backported now.

**Pull request merged**
