### PR TITLE
docs: bump nmd

### PR DESCRIPTION
**Pull request by rycee**
### Description

Bump nmd to make prompts unselectable in shell session program listings.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
small question: did you think about moving nmd to github, too to make it easier to find and better integrate into the workflow? I think GitHub allows cross closing issues and similar.

**Comment by rycee** [comment]
@SuperSandro2000 I'm actually in the process of slowly migrating to [sourcehut](https://sourcehut.org/) so I'm unlikely to move repos to GitHub or make new repos here. Basically, I'm very skeptical of Microsoft's intentions with GitHub and I worry about the virtual monopoly status of GitHub, so I'm happy to use alternative forges that try new interesting things. And I think sourcehut is the most interesting at the moment.

I have no intention to move HM away from it's current location on GitHub, though, in case you or anybody get worried 🙂 I do mirror HM to GitLab and run a bit of CI on it there.

**Comment by SuperSandro2000** [comment]
FYI sourcehut will be paid when it leaves alpha.

**Comment by rycee** [comment]
Yep, I've actually chosen to pay for it already. Overall, I think the pricing is the main concern I have about sourcehut, in particular I'm hoping they will keep a flexible pricing model so that it remains accessible to everybody. I don't mind paying a higher price if it allows somebody with less money to spend access the same features. In the long run I would love to see something like a federated sourcehut like forge, that would be pretty sweet.

**Pull request merged**
