### PR TITLE
foot: fix error when startup with fish

### LINKED ISSUE #3940: bug:  footclient reports error when startup with fish shell
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When starting a Foot server using systemd service with hm module option, if the shell is Fish, an error will be displayed every time a Foot client is started. 

However, if the service is stopped and a Foot server is manually started in the terminal, then starting the client works fine.

### error message be like:
```console
/nix/store/rnkas52f8868g1hjdlldbvh6snm3pglv-bash-5.2-p15/bin/bash: line 1: env: command not found
set: Tried to change the read-only variable 'PWD'
set: Tried to change the read-only variable 'SHLVL'
```

### My foot config relative part:
```shell

      main = {
        font = "SF Mono:size=13:style=Medium";
        dpi-aware = "yes";
        term = "foot";
        pad = "8x8";
        shell = "${pkgs.fish}/bin/fish";
        login-shell = "no";
      };

```

BTW my login shell is bash, tested with fish shell startup with minimal configurations.

### AND one possible fix:
```patch
From a166893f0982879753a659b590fa7b299f49d602 Mon Sep 17 00:00:00 2001
From: oluceps <i@oluceps.uk>
Date: Tue, 2 May 2023 16:41:41 +0800
Subject: [PATCH] foot: fix error when startup with fish

---
 modules/programs/foot.nix | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/modules/programs/foot.nix b/modules/programs/foot.nix
index 2b08f3ac..544fcf57 100644
--- a/modules/programs/foot.nix
+++ b/modules/programs/foot.nix
@@ -7,7 +7,8 @@ let
   cfg = config.programs.foot;
   iniFormat = pkgs.formats.ini { };
 
-in {
+in
+{
   meta.maintainers = with lib.maintainers; [ plabadens ];
 
   options.programs.foot = {
@@ -69,6 +70,7 @@ in {
         };
 
         Service = {
+          Environment = "PATH=/run/current-system/sw/bin/";
           ExecStart = "${cfg.package}/bin/foot --server";
           Restart = "on-failure";
           OOMPolicy = "continue";
-- 
2.40.0

```

Works well after that. But I don't know if this is dirty.

### Maintainer CC

cc @plabadens 

### System information

```markdown
> nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.0, NixOS, 23.05 (Stoat), 23.05.20230428.937a9d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by oluceps**
### Description
close #3940

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by ncfavier** [comment]
If `foot` depends on `coreutils` then it should be wrapped appropriately in nixpkgs. However I'm not sure that's the case since it works fine for everyone else.

Do you have any idea where the error you're reporting could be coming from?

**Comment by oluceps** [comment]
> If `foot` depends on `coreutils` then it should be wrapped appropriately in nixpkgs. However I'm not sure that's the case since it works fine for everyone else.
> 
> Do you have any idea where the error you're reporting could be coming from?

This error only occurs while using `foot with server mode` +  `fish`. I've tested `zsh` and `bash`, and they work normally, and non-daemon foot works with fish as well.

It seems `fish` requires `bash` to exec `env`, which is in coreutils,  to get env vars at startup or something else, at least the error shows that. Idk if someone else could reproduce this error, with minimal fish config and foot client as I did.

Maybe It's proper way to add an individual option for fish shell in `options.programs.foot` if that issue could be reproduced?

**Comment by oluceps** [comment]
FWIW this is my configuration producing this error, [fish](https://github.com/oluceps/nixos-config/blob/b101208aac0a44f72f3bedb8a4175ed28bd64f1e/home/programs/fish/default.nix) and [foot](https://github.com/oluceps/nixos-config/blame/6fab42ccb5f031e99e284812a123b30a065160b2/home/programs/foot/default.nix), only difference is `server.enable = true`

**Comment by ncfavier** [comment]
Your error points me to https://github.com/fish-shell/fish-shell/issues/3120: do you have anything interesting in `.config/fish`? Could you post the output of `fish -d4`?

**Comment by oluceps** [comment]
> Your error points me to [fish-shell/fish-shell#3120](https://github.com/fish-shell/fish-shell/issues/3120): do you have anything interesting in `.config/fish`? Could you post the output of `fish -d4`?

My `.config/fish`:

```console
persist.20230506T1624/home/user/.config/fish     
> tree
.
├── completions
├── config.fish -> /nix/store/124f487wxa1syww8xp1sghjpb6h4ycyp-home-manager-files/.config/fish/config.fish
├── fish_variables
└── functions
    ├── dec.fish -> /nix/store/124f487wxa1syww8xp1sghjpb6h4ycyp-home-manager-files/.config/fish/functions/dec.fish
    ├── ekey.fish -> /nix/store/124f487wxa1syww8xp1sghjpb6h4ycyp-home-manager-files/.config/fish/functions/ekey.fish
    ├── extract.fish -> /nix/store/124f487wxa1syww8xp1sghjpb6h4ycyp-home-manager-files/.config/fish/functions/extract.fish
    ├── fish_greeting.fish -> /nix/store/124f487wxa1syww8xp1sghjpb6h4ycyp-home-manager-files/.config/fish/functions/fish_greeting.fish
    └── update_cwd_osc.fish -> /nix/store/124f487wxa1syww8xp1sghjpb6h4ycyp-home-manager-files/.config/fish/functions/update_cwd_osc.fish

2 directories, 7 files
```

```console
persist.20230506T1624/home/user/.config/fish     
> cat fish_variables 
# This file contains fish universal variable definitions.
# VERSION: 3.0
SETUVAR __fish_initialized:3400
SETUVAR fish_color_host_remote:yellow
SETUVAR fish_color_status:red
SETUVAR fish_key_bindings:fish_vi_key_bindings
```
And [config files](https://github.com/oluceps/Log-848689f8/tree/main/fish) from `.config/fish`: 

All configurations are managed by hm except file `fish_variables` (which is auto-generated at runtime), the error msg is the same after I remove it. [My foot hm config](https://github.com/oluceps/nixos-config/blob/b101208aac0a44f72f3bedb8a4175ed28bd64f1e/home/programs/fish/default.nix) looks have no anything could potentially change those variables.

Result of `fish -d4` exec on foot client:
```console
> fish -d4
Failed to match debug category: 4
Debug enabled for category: debug
Debug enabled for category: error
Debug enabled for category: exec
Debug enabled for category: warning
Debug enabled for category: warning-path
```

**Comment by ncfavier** [comment]
My guess would be the foreign-env fish plugin then, as that seems to call `env` and use `set`. Either the plugin should be patched in nixpkgs to hardcode the path to `env`, or you should make sure it only runs *after* your initial `PATH` is set up.

**Comment by ncfavier** [comment]
Should be as simple as adding a line [here](https://github.com/NixOS/nixpkgs/blob/3e313808bd2e0a0669430787fb22e43b2f4bf8bf/pkgs/shells/fish/plugins/foreign-env/default.nix#L16-L21). Closing.

**Comment by oluceps** [comment]
Solved. Thanks a lot!

**Pull request closed without merging**
