### PR TITLE
flake.nix: Add packages and defaultPackage outputs

### PR DESCRIPTION
**Pull request by i077**
### Description

Modify flake.nix to provide the the `home-manager` binary for each supported platform as mentioned in https://github.com/nix-community/home-manager/pull/1856#issuecomment-815077415. "Supported platforms" is equivalent to the set provided in `meta.platforms` in the home-manager derivation, `lib.platforms.unix`.

**One problem**: `nix run github:nix-community/home-manager/pull/1913/head` does not run because nix wants to write a lock file. Passing `--no-write-lock-file` fixes this, but this must be passed on each invocation of `nix run`. To fix this, we could start to track `flake.lock` (and I think this will be necessary if we want to provide a package output), but I'm hesitant to do so mostly because it would have to be updated every so often. Probably worth discussing before merging this.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by edrex** [comment]
Is there something special about home-manager that makes the lock file problematic?

**Comment by berbiche** [comment]
> Is there something special about home-manager that makes the lock file problematic?

Not to my knowledge.

The original motivation in commit 6cf6b587b575493e7718bf08b209013d7dcf4d58:
> No flake.lock is added because the only input (nixpkgs) will almost always be overridden, and currently Home Manager's testing and verification is not flake based.

I would be open to have a flake.lock committed in another PR because we'll also need a github action to udpate the flake.lock and these things fall outside of this PR.

**Comment by i077** [comment]
> we'll also need a github action to udpate the flake.lock and these things fall outside of this PR.

Would you be fine with the action just directly committing updates to flake.lock to master each week or something?

**Comment by teto** [comment]
I would prefer for it to track nixos-unstable to limit the number of issues. I think we should indeed have a lock file. I remember reading that `--override-input`  will disable update of the lockfile which should make it easier to run.

**Review by berbiche — APPROVED** [review]
LGTM!

**Comment by berbiche** [comment]
I think it's fine to merge this without the documentation in the README for the moment.

**Comment by i077** [comment]
@berbiche do we still want to consider adding in a flake.lock? I can start working on a new branch to add one (and a new CI workflow to update it).

**Comment by berbiche** [comment]
> @berbiche do we still want to consider adding in a flake.lock? I can start working on a new branch to add one (and a new CI workflow to update it).

Let's see what @rycee thinks of this first. Having a bot that updates the flake.lock nixpkgs' while running regression tests for different new nixpkgs-unstable/nixos-unstable/nixos-unstable-small  channels (depending which on which one we end up using) would be nice.

**Comment by teto** [comment]
I think we should: not having a lockfile triggers some nix warnings and would be a standard way for the users to get a commit for which home-manager is guaranteed to work. We could run the tests against both that lock and an overridden one.

**Comment by rycee** [comment]
I have no insightful input, I've never used flakes or know particularly much about them. But I wouldn't want HM to pin people to a particular Nixpkgs commit. Automatic updates of a lockfile should be fine, as long as it's not too frequent and spam commits all over, perhaps at most once per day as a general rule?

**Comment by i077** [comment]
I was thinking once per week so as not to spam the history with update commits. I don't see a need to _closely_ follow unstable, especially if 1) the only thing that needs the flake.lock is a shell script and 2) people should be overriding home-manager's nixpkgs input in their own flakes anyways.

I can get to work later this week on adding all this and updating the README to mention overriding the input as well.

**Comment by berbiche** [comment]
> I was thinking once per week so as not to spam the history with update commits. I don't see a need to _closely_ follow unstable, especially if 1) the only thing that needs the flake.lock is a shell script and 2) people should be overriding home-manager's nixpkgs input in their own flakes anyways.

I agree, though I would go for twice a week because if there's a failure when updating the nixpkgs revision then flake.lock could remain pinned to a specific version for two weeks or until a contributor updates the version.

**Comment by kclejeune** [comment]
> > I was thinking once per week so as not to spam the history with update commits. I don't see a need to _closely_ follow unstable, especially if 1) the only thing that needs the flake.lock is a shell script and 2) people should be overriding home-manager's nixpkgs input in their own flakes anyways.
> 
> I agree, though I would go for twice a week because if there's a failure when updating the nixpkgs revision then flake.lock could remain pinned to a specific version for two weeks or until a contributor updates the version.

Not sure exactly what you had in mind, but @i077 and I both use [this workflow](https://github.com/kclejeune/system/blob/master/.github/workflows/update.yml) in our personal repos to manage flake updates. It commits flake updates to a new branch and opens a pull request rather than merging directly to master so that you can run standard branch protection checks against it. 

Seems like it could work pretty well here. Thoughts?

**Comment by teto** [comment]
@kclejeune I like it

**Pull request merged**
