### PR TITLE
tmux: allow setting default-shell before new-session

### PR DESCRIPTION
**Pull request by expipiplus1**

### CODE REVIEW

**Comment by rycee** [comment]
Thanks for the contribution! @kalbasit, seems ok to you?

**Comment by stites** [comment]
new-session was also causing problems with my keybindings to synchronize-panes. Maybe a better solution is to put new-session at the end of the .tmux.conf (including all plugins and extraConfigs).

**Comment by expipiplus1** [comment]
Fine by me!

**Comment by expipiplus1** [comment]
@jorsn Is this still necessary after https://github.com/rycee/home-manager/pull/945?

**Comment by jorsn** [comment]
> @jorsn Is this still necessary after #945?

Well, kind of: At the moment, if you use the home-manager option `programs.tmux.newSession`, then you have not possibility of setting the default shell before the `new-session`. If you manually call `new-session` in the `programs.tmux.extraConfig`, then you can.

For a custom default shell set before the `new-session` call by `programs.tmux.newSession` you need to either add the option `defaultShell` as this PR does, or you put the `new-session` after the `extraConfig`. I don't know whether this can be a problem. It might be.

**Comment by expipiplus1** [comment]
cool, in that case is it possible to get this merged? I've rebased.

**Comment by expipiplus1** [comment]
Is it possible to merge this? I've been using it for a year without issue.

**Review by berbiche — APPROVED** [review]

**Comment by berbiche** [comment]
LGTM!

**Comment by rycee** [comment]
Thanks! Merged to master.

**Comment by expipiplus1** [comment]
Thanks!

**Pull request merged**
