### PR TITLE
podman-container: fix test

### PR DESCRIPTION
**Pull request by GaetanLepage**
### Description

Fix the current CI failure by adapting the relevant snapshot.

### Checklist

- [ ] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

### CODE REVIEW

**Comment by khaneliman** [comment]
```diff
podman-network: FAILED
Expected /nix/store/58fhlzb12kv3lyzbx2lkyl323swkd0dy-nmt-report-podman-network/normalized/podman-my-net-network.service to be same as /nix/store/nzdfwixn2d83dbfrf7znkd4dq26rqig0-network-expected.service but were different:
--- actual
+++ expected
@@ -23,14 +23,11 @@
 ExecStartPre=/nix/store/00000000000000000000000000000000-await-podman-unshare
 RemainAfterExit=yes
 TimeoutStartSec=15
-ExecStart=/nix/store/00000000000000000000000000000000-podman/bin/podman network create --ignore --subnet 192.168.1.0/24 --gateway 192.168.1.1 --opt isolate=true --label nix.home-manager.managed=true --ipam-driver dhcp --dns=192.168.55.1 --log-level=debug my-net
-SyslogIdentifier=%N
+ExecStart=/nix/store/00000000000000000000000000000000-podman/bin/podman network create --ignore --subnet=192.168.1.0/24 --gateway=192.168.1.1 --opt isolate=true --label nix.home-manager.managed=true --ipam-driver dhcp --dns=192.168.55.1 --log-level=debug my-net
 Type=oneshot
+SyslogIdentifier=%N
 
 [Unit]
-Wants=podman-user-wait-network-online.service
-After=podman-user-wait-network-online.service
 After=network.target
 Description=Service for network my-net
-SourcePath=/nix/store/00000000000000000000000000000000-home-network-podman-my-net/quadlets/podman-my-net.network
 RequiresMountsFor=%t/containers
For further reference please introspect /nix/store/58fhlzb12kv3lyzbx2lkyl323swkd0dy-nmt-report-podman-network

**Comment by bamhm182** [comment]
I lumped the fixes into [this PR](https://github.com/nix-community/home-manager/pull/6137) (#6137) which also adds a few additional quadlets.

Should these have been separate? @n-hass

**Comment by bamhm182** [comment]
As I was digging into podman 5.3.0's changes, I realized that the new `podman-user-wait-network-online.service` dependency added to these configs is broken on NixOS because it can't resolve `sh` or `systemctl`. I have made a PR on @GaetanLepage 's fork [here](https://github.com/GaetanLepage/home-manager/pull/1) to resolve the remaining issues Podman 5.3.0 has brought into this module.

**Comment by GaetanLepage** [comment]
Yeah ! The CI passes !!! Thanks @bamhm182 :)

**Comment by GaetanLepage** [comment]
cc @rycee

**Comment by n-hass** [comment]
yep LGTM

**Review by n-hass — APPROVED** [review]

**Comment by rycee** [comment]
Thanks for the fix! Merged to master now 🙂

**Pull request merged**
