### PR TITLE
neovim: drop python2 support

### PR DESCRIPTION
**Pull request by dotlambda**
### Description
Nixpkgs did the same in https://github.com/NixOS/nixpkgs/pull/121339.

### Checklist

- [ ] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by dotlambda** [comment]
CI will not succeed until nixos-unstable advances to include https://github.com/NixOS/nixpkgs/commit/d942d4473d1165cf9d8a1171bbad154f77239ba0.

**Comment by sumnerevans** [comment]
@dotlambda it's currently failing due to the formatting being wrong. Can you fix that so that when nixpkgs advances, we are good to go on this side?

**Review by sumnerevans — APPROVED** [review]
https://github.com/NixOS/nixpkgs/pull/121339 has [made it to `nixos-unstable`](https://nixpk.gs/pr-tracker.html?pr=121339). The build is passing, so I'm going to merge. Thanks for the contribution @dotlambda

**Comment by simonvpe** [comment]
This breaks for me, but I don't specify any of those options in my config.
```
[ERROR] 
[ERROR] error: Python2 support has been removed from neovim, please remove withPython and extraPythonPackages.
[ERROR] (use '--show-trace' to show detailed location information)
[ERROR] 
```

**Comment by sumnerevans** [comment]
@simonvpe have you updated all of your channels (home manager and global/system nixos channe)? They need to be in sync.

**Pull request merged**
