### PR TITLE
fontconfig: add defaultFonts.* options

### LINKED ISSUE #2186: Default fonts
### Issue description

Would it make sense to be able to have home-wide default fonts? For example, a default... monospace font? A default serif font? A default sans-serif font? I'd like that a lot. It would spare me the trouble of configuring fonts in various other packages, such as the window manager, the terminal, etc.

I see that [in NixOS this is possible using fontconfig](https://search.nixos.org/options?channel=21.05&from=0&size=50&sort=relevance&query=fonts.fontconfig.defaultFonts).

#### Maintainer CC

@rycee.

### PR DESCRIPTION
**Pull request by ilkecan**
### Description

Adds defaultFonts.* options to specify the default font per-user. Closes #2186 

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Review by berbiche — APPROVED** [review]
Thanks for the contribution!

LGTM.

**Comment by ralismark** [comment]
Just wondering, what else needs to be done for this PR? I rebased onto master and ran `nix-shell --pure tests -A run.all` and the only failure was `firefox-profile-settings`, which seems unrelated.

**Review by somasis — APPROVED** [review]

**Comment by Aleksanaa** [comment]
Still important to me.

**Comment by trueNAHO** [comment]
I can confirm this PR works.

However, support for arbitrary settings is lacking. Currently, 

https://github.com/nix-community/home-manager/pull/2732/files#diff-009fe001905585716178d9bc500b9ca3d27d17ae0f4d019f6f9864608884c39bR36-R77

only declares the following entries:

https://github.com/nix-community/home-manager/pull/2732/files#diff-009fe001905585716178d9bc500b9ca3d27d17ae0f4d019f6f9864608884c39bR157-R160

For reference, the [git module](https://github.com/nix-community/home-manager/blob/9f9e277b60a6e6915ad3a129e06861044b50fdf2/modules/programs/git.nix) implements arbitrary settings with its [`extraConfig`](https://github.com/nix-community/home-manager/blob/9f9e277b60a6e6915ad3a129e06861044b50fdf2/modules/programs/git.nix#L185-L196) property:

https://github.com/nix-community/home-manager/blob/9f9e277b60a6e6915ad3a129e06861044b50fdf2/modules/programs/git.nix#L185-L196

Potentially related: https://github.com/nix-community/home-manager/pull/1268

**Comment by Aleksanaa** [comment]
Still important

**Review by trueNAHO — APPROVED** [review]

**Comment by Aleksanaa** [comment]
THIS IS ALWAYS IMPORTANT!

**Comment by trueNAHO** [comment]
Considering this PR is sadly not getting merged any time soon, it might make sense to supersede this PR with a new one that addresses https://github.com/nix-community/home-manager/pull/2732#issuecomment-1715387349.

**Review by trueNAHO — CHANGES_REQUESTED** [review]
The following comment should be added to the top of this file:

```nix
/*
This module is heavily inspired by the NixOS implementation [1].

[1]: https://github.com/NixOS/nixpkgs/blob/23.11/nixos/modules/config/fonts/fontconfig.nix
*/
```

Note: Based on https://github.com/NixOS/nixpkgs/blob/23.11/nixos/modules/config/fonts/fontconfig.nix, the proposal from https://github.com/nix-community/home-manager/pull/2732#issuecomment-1715387349 is non-essential and should be added in a follow-up PR, if requested.

**Comment by rycee** [comment]
Apologies for the delay. Made some final cleanups based on @trueNAHO's comments and merged to master. Thanks!

**Comment by Aleksanaa** [comment]
Greatly appreciated 👍

**Pull request merged**
