### PR TITLE
nixos: fix fontconfig mkDefault call

### PR DESCRIPTION
**Pull request by andresilva**
### Description

Fixes https://github.com/nix-community/home-manager/commit/cd3dd2188c19416bc70d9703f84e07a0646af5bf#r75997641. 

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Review by maxhbr — APPROVED** [review]
LGTM and would solve my current problems ;)

**Comment by johnrichardrinehart** [comment]
Good job! Cleans me up!

**Comment by maxhbr** [comment]
FYI: a temporary mitigation:
```diff
diff --git a/flake.nix b/flake.nix
index e9b199dad..f56b7406a 100644
--- a/flake.nix
+++ b/flake.nix
-    home.url = "github:nix-community/home-manager";
+    home.url = "github:nix-community/home-manager/70824bb5c790b820b189f62f643f795b1d2ade2e";
```
where `70824bb5c790b820b189f62f643f795b1d2ade2e` was just a random previous commit working on my machine

**Review by felschr — APPROVED** [review]

**Comment by water-sucks** [comment]
> FYI: a temporary mitigation:
> 
> ```diff
> diff --git a/flake.nix b/flake.nix
> index e9b199dad..f56b7406a 100644
> --- a/flake.nix
> +++ b/flake.nix
> -    home.url = "github:nix-community/home-manager";
> +    home.url = "github:nix-community/home-manager/70824bb5c790b820b189f62f643f795b1d2ade2e";
> ```
> 
> where `70824bb5c790b820b189f62f643f795b1d2ade2e` was just a random previous commit working on my machine

I didn't want to change the content of `flake.nix` explicitly and only wanted to change the lock temporarily, so I did `nix flake update --override-input home "github:nix-community/home-manager/70824bb5c790b820b189f62f643f795b1d2ade2e"` instead; both do work though

**Comment by andresilva** [comment]
@teto Sorry to ping you, but since you merged #3014 it would be helpful if you could merge this PR as well.

**Comment by teto** [comment]
arf when I reviewed it, it seemed odd but I trusted you, let's add a test next time.

**Pull request merged**
