### PR TITLE
mu: add package option

### PR DESCRIPTION
**Pull request by jian-lin**
### Checklist

- [X] Change is backwards compatible.

- [X] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [X] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC

@KarlJoad

### CODE REVIEW

**Comment by jian-lin** [comment]
Do you have any ideas why `getExe cfg.package` evals to `@mu@/bin/dummy` in test? @rycee @ncfavier 

It evals to the right thing: `/nix/store/n9v56iqlsi3vlf9dl86p6n2ywszzr85g-mu-1.10.3/bin/mu` if I build my NixOS system with this PR.

**Comment by jian-lin** [comment]
I figured out and fixed the test.

**Comment by KarlJoad** [comment]
This _looks_ fine to me. But what is the purpose of this change? You left the "Description" box blank at the top of the PR.

**Comment by jian-lin** [comment]
FYI, adding a `package` option seems to a [convention](https://github.com/NixOS/nixpkgs/issues/50476#issuecomment-637841528).

**Comment by quinn-dougherty** [comment]
This gave me another way forward for debugging https://discourse.nixos.org/t/doom-emacs-and-mu4e/21222/3?u=quinn-dougherty -- so thanks!

**Pull request merged**
