### PR TITLE
flake: remove default stateVersion in lib.homeManagerConfiguration

### PR DESCRIPTION
**Pull request by berbiche**
### Description

Either the default stateVersion is always updated to be the lastest version or it's not defined.

See #2622 and https://github.com/nix-community/home-manager/pull/2510#pullrequestreview-816315847

This is not backwards compatible.

### Checklist

- [ ] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by rycee** [comment]
Agreed, we should remove the default state version. Additionally, I think we should remove the default for `home.stateVersion` as well. See https://github.com/NixOS/nixpkgs/pull/149877 for a corresponding issue on the NixOS side.

**Comment by terlar** [comment]
As the person adding this default for the flake function, I’m giving this my blessing as well.

I also think the suggestion to remove the default for `home.stateVersion` is good. I guess it might only be confusing to a first time user what to put there, so probably some docs would need to be updated to emphasise that.

**Comment by berbiche** [comment]
> Additionally, I think we should remove the default for home.stateVersion as well.

I removed the option but I'm not sure how to handle all the tests that do not provide a default value.
I can set the value manually in each file to `18.09` but there's probably a better way to change this value for all tests?

**Comment by berbiche** [comment]
Friendly ping @rycee

**Comment by LunNova** [comment]
Why require it to be set as an arg at all here?

You can set it in `configuration` or `extraModules`, and requiring it as an arg means you can't set it elsewhere without either using mkForce and leaving a dummy value here or keeping them in sync.

**Comment by LunNova** [comment]
Related: #2720

**Comment by berbiche** [comment]
> Why require it to be set as an arg at all here?

Right, I am not sure what would be the best "API".
I personally I like that it's part of the function parameters because it makes it explicit in the declaration "This Home Manager configuration is compatible with this "state" version".

> without either using mkForce and leaving a dummy value here

The value can be set as "default" with `mkDefault`, this would allow you to override the value without `mkForce`.

**Pull request closed without merging**
