### PR TITLE
taskwarrior: don't create dataLocation with home.file

### LINKED ISSUE #2207: bug: programs.taskwarrior.dataLocation = /absolute/path creates $HOME/absolute/path
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

My taskwarrior configuration uses an absolute path for `programs.taskwarrior.dataLocation` (I point it to `/var/lib/syncthing/taskwarrior-data/.task`).

The result is a properly configured path in `taskrc`, but also the unfortunate side effect of creating `$HOME/absolute/path/.keep`, which is a symlink to the nix store. The path is wrongly placed in $HOME instead of /absolute/path (and I don't want the .keep symlink either).

`programs.taskwarrior.dataLocation` is mapped to `home.file`, so we should perhaps discuss how that API should handle abspaths.

Perhaps the simpler short-term solution is stopping `programs.taskwarrior.dataLocation` from _creating_ that path (taskwarrior will create it on first use, I hope).

### Maintainer CC

@rycee for `modules/files.nix` and @minijackson for `modules/programs/taskwarrior.nix`.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.4.122, NixOS, 20.09.git.359e654 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-20.03.1950.48723f48ab9"`
 - nixpkgs: `/etc/current-nixpkgs`
```

### PR DESCRIPTION
**Pull request by bjornfor**
### Description
My use-case is having programs.taskwarrior.dataLocation =
/absolute/path (outside of $HOME), but the current implementation
wrongly creates $HOME/absolute/path (due to how home.file is
implemented).

Since taskwarrior creates the dataLocation automatically on first run,
there is actually no need for HM to create that directory.

Additional benefit, the .keep symlink that HM creates as a side-effect
no longer appears in the taskwarrior data directory.

Fixes #2207.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`. I'm still on nixpkgs-20.09 and that command is impure so it fails. I tried with `NIX_PATH=nixpkgs=... nix-shell ...` but then my local overlays leak into the tests breaking them. I patched some (`import <nixpkgs> {}` -> `import <nixpkgs> { config = {}; overlays = []; }` but I guess I didn't catch them all.)

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by rycee** [comment]
Thanks, merged to master!

**Comment by bjornfor** [comment]
@rycee: Can I ask for a backport to release-21.05?

**Comment by rycee** [comment]
@bjornfor No worries, it is merged to the 21.05 branch now. Please give it a try.

**Comment by bjornfor** [comment]
Will do, thanks! (I already tested it against 20.09.)

**Pull request merged**
