### PR TITLE
Introduce new lib-function for lists to filter out empty elements

### PR DESCRIPTION
**Pull request by SebTM**
### Description
Related to #2314
Moved function needed by this PR because its providing basic/general functionality and therefore should be located in lib

### Checklist

- [X] Change is backwards compatible.

- [X] Code formatted with `./format`.

- [X] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [X] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Review by sumnerevans — APPROVED** [review]

**Comment by rycee** [comment]
I think it's best to avoid introducing this function, I think it is too ambiguous as to what "empty" means in this context. For example, why not remove empty lists as well? And the flatten functionality seems arbitrary. So it seems to me that this function is not actually generally useful but rather intended for a specific use-case.

I'm thinking that perhaps a function like

``` nix
removeAny [3 4] [ 1 3 4 3 ]
# => [ 1 ]
```

to match the remove function may be nice.

**Comment by SebTM** [comment]
Hmm, the function/separation outside the module happened after discussion in the above PR, as the "notEmpty"-function comes from "[xidlehook](https://github.com/nix-community/home-manager/blob/master/modules/services/xidlehook.nix#L10)" it felt like a more often use-case with the below examples:
 - https://github.com/nix-community/home-manager/blob/master/modules/programs/neovim.nix#L49 / 52
 - https://github.com/nix-community/home-manager/blob/master/modules/services/fnott.nix#L9
 - https://github.com/nix-community/home-manager/blob/master/modules/programs/mbsync.nix#L161 / 180
 - (unsure) https://github.com/nix-community/home-manager/blob/master/modules/programs/skim.nix#L108 (with your adjustments about empty sets)

The goal with providing this function was to reduce the possible duplicate code and more common handling of these recurring situations, as far as I understand.

I understand your point with the naming, we can rename and extend it to also filter empty lists 👍🏻 
I'm not sure how to understand "And the flatten functionality seems arbitrary" can you explain a bit more, please?

Thanks for your review and feedback, I appreciate it ⭐

**Comment by rycee** [comment]
@SebTM About the flatten, I think that the flattening is so different from the `notEmpty` naming that it would have to be included in the name, similar to how `concat` is part of `concatStringsSep`. Specifically, with the existing naming I would expect

``` nix
notEmpty [ [ "" 34 ] [] null "s" ]
```

to return `[ [ "" 34 ] "s" ]`, not `[ 34 "s" ]`. So perhaps something like `flattenRemoveEmpty` and `removeEmpty` (for the non-flattening version of the function).

I'm not super convinced about the necessity of these functions, though. When it only is empty strings that are removed then I think `remove ""` is more straight-forward and clear. I created the above PR to make that change. The filter remains for cases where you want to remove, for example, both `null` and `""` values. For those perhaps the `removeAny` (alternatively named `removes`) function would be simplest. I.e., something like

``` nix
removes [ "" null ] listOfStuff
```

The flattening could be done explicitly

``` nix
removes [ "" null ] (flatten listOfStuff)
```

or with a custom function

``` nix
flattenRemoves [ "" null ] listOfStuff
```

**Comment by SebTM** [comment]
Seems to be not really needed as I could use `lists.subtractLists` without Problems - see other PR :)

**Comment by SebTM** [comment]
Seems to be not really needed as I could use `lists.subtractLists` without Problems - see #2314  :)

**Pull request closed without merging**
