### PR TITLE
Add infrastructure for contacts and calendars

### PR DESCRIPTION
**Pull request by teto**
This also adds the modules

  - programs.vdirsyncer,
  - programs.khal, and
  - services.vdirsyncer

that integrate with the new infrastructure.

Co-authored-by: Andrew Scott <3648487+ayyjayess@users.noreply.github.com>
Co-authored-by: Sebastian Zivota <sebastian.zivota@mailbox.org>

### Description

This is a rebased version of the longstanding PR ( > 3 years ?) made to add contact and calendar support.
I've commented out "locale" support for khal since it was causing issues.

With it in its current state I was able to configure vdirsyncer and khal.
My proposition is to merge this wiht all its faults otherwise we can still wait 4 years before having  anything working.
We have 6 months before release to iron things out and until then we make it clear that the module is experimental.

### Checklist

- [ ] Change is backwards compatible.

- [ ] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

### CODE REVIEW

**Comment by ncfavier** [comment]
What about https://github.com/nix-community/home-manager/pull/3912?

**Comment by teto** [comment]
#3912 is nowhere close to this old contact branch. This is much better as it generates the config for you.

**Comment by teto** [comment]
also just in case you are not on the chat, I actually asked on matrix before merging. To sum up it's not perfect but let's merge and make it as good as the mail infra https://github.com/nix-community/home-manager/issues/2335#issuecomment-1588127066

**Comment by DanielSiepmann** [comment]
Is there a way to exclude the new WIP modules in my local setup?
I already have a working vdirsync module for myself. This now conflicts with the new upstream provided by this PR.
And I can't migrate to upstream, due to still incomplete accounts modules.

That's why I would like to exclude the upstream vdirsync until its done.

**Comment by ncfavier** [comment]
`disabledModules = [ "programs/vdirsyncer.nix" ];` should do it, at the same level as `imports`, `config`, `options`...

**Comment by teto** [comment]
@DanielSiepmann how does your module compare ? anything we could merge ?

> And I can't migrate to upstream, due to still incomplete accounts modules.

what part do you miss, especially compared to yours ? Note that I messed up when merging. Does https://github.com/nix-community/home-manager/pull/4087 fix your situation ?

**Comment by ncfavier** [comment]
`disabledModules` is supposed to look for relative paths in `modulesPath`, which is `<home-manager/modules>`, so your module should be left alone.

**Comment by teto** [comment]
you might be better off renaming your module, so you can try both.

**Comment by DanielSiepmann** [comment]
@teto
> Does #4087 fix your situation ?
I guess yes, as I end up in `error: The option `accounts.calendar' does not exist. Definition values`, will give it a try (later) and see whether I can migrate to the upstream :) And will provide feedback if I miss anything.

@ncfavier Thanks, it indeed works.

**Comment by Janik-Haag** [comment]
@teto do you mind sharing your config I can't get it running in the current state ^^

my current config is this but the accounts module dosn't create a config for vdirsyncer.
```nix
{ ... }:
{
  services.vdirsyncer.enable = true;
  accounts.contact.basePath = ".con";
  accounts.calendar.basePath = ".cal";
  accounts.calendar.accounts.nerdberg = {
    khal = {
      enable = true;
      color = null;
      readOnly = true;
      type = "calendar";
    };
    local.type = "filesystem";
    local.fileExt = ".ics";
    name = "Nerdberg";
    remote = {
      type = "http";
      url = "https://kalender.nerdberg.de/events.ics";
    };
    vdirsyncer = {
      enable = true;
      collections = null;
      conflictResolution = "remote wins";
    };
  };
}
```

**Comment by Janik-Haag** [comment]
also on another note:  we have some stuff that is using local and other stuff locale which seems like it should be called the same every where, and I think there is a copy paste error:
image

**Comment by teto** [comment]
@Janik-Haag I would recommand first crafting a working configuration manually and once you have it working convert it to home-manager format so you can spot what is missing. My config is here https://github.com/teto/home/blob/main/hm/profiles/vdirsyncer.nix .

could you point in the code the typo ? I am not sure if you refer to `locale` as in LANG or LC_MONETARY variables

**Pull request merged**
