### PR TITLE
services/kanshi: add module example

### PR DESCRIPTION
**Pull request by asymmetric**
### Description

Adds documentation for the `services.kanshi.profiles` submodule.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Review by sumnerevans — COMMENTED** [review]
I'm really not sure how necessary this is since the various options of the submodule are already documented.

**Comment by asymmetric** [comment]
@sumnerevans for example, it's not obvious (without looking at the code) that the `criteria` should not have the word `output` in it, since it will be added automatically.

**Comment by sumnerevans** [comment]
Ah, I see. I think it makes a lot more sense to put the documentation on each of the individual options rather than the module itself.

**Review by berbiche — APPROVED** [review]
LGTM!

**Pull request merged**
