### PR TITLE
psd: add missing module config options

### LINKED ISSUE #5454: bug: Profile-sync-daemon not working correctly
### Are you following the right branch?

- [x] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Currently the newly-added `services.psd.enable` option doesn't work correctly due to three issues.

**First issue**, the psd daemon will not work, since the base config files in `$HOME/.config/psd` are not created, the daemon will always exit with:
```
First time running psd so please edit /home/USER/.config/psd/psd.conf to your liking and run again.
```

**Second issue**, if you manually add the config file, it always fails with:
```
profile-sync-daemon[6398]:   is not a supported browser. Check config file for typos: /home/USER/.config/psd/psd.conf
```
I generated the config file simply by running `psd` once.
This might be be a bug in psd, since if no browsers are added to the config, it should automatically manage all browsers present on the system.

**Third issue**, if you manually add a browser to the config, it fails, since the script PSD runs can't find needed commands in the environment.
```
/nix/store/nycg6pa28kh4hk1nmm6vh73gvd758vav-profile-sync-daemon-6.50/share/psd/browsers/firefox: line 15: grep: command not found
/nix/store/nycg6pa28kh4hk1nmm6vh73gvd758vav-profile-sync-daemon-6.50/share/psd/browsers/firefox: line 15: sed: command not found
/nix/store/nycg6pa28kh4hk1nmm6vh73gvd758vav-profile-sync-daemon-6.50/bin/profile-sync-daemon: line 390: id: command not found
```

### Maintainer CC

@danjujan
@rycee

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.9.1, NixOS, 24.11 (Vicuña), 24.11.20240523.3305b2b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/3qi6zkjzggmilf1sx4b979ym6fxnqsjl-source`
```

### PR DESCRIPTION
**Pull request by TheStachelfisch**
### Description

This change adds configurable options to psd and creates the corresponding config file, it also adds missing packages to the envPath. 
Previously the config file would not be automatically created, which broke psd and made it not function like it should.

I added config options that I think are relevant. I deliberately left out options like `USE_OVERLAYFS` and `USE_SUSPSYNC` as they have additional dependencies that would need to have assertions to check if they are met.

Closes #5454 

### Checklist

- [X] Change is backwards compatible.

- [X] Code formatted with `./format`.

- [X] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [X] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [X] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC
@danjujan

### CODE REVIEW

**Comment by TheStachelfisch** [comment]
@rycee Can this be merged? I've been trying it out for the past few weeks and it's been working flawlessly.
Without this PR, psd does not work at all.

**Comment by TheStachelfisch** [comment]
> @TheStachelfisch I think the pipeline is stuck. Could you please trigger it again?

Please, go ahead

**Comment by TheStachelfisch** [comment]
Another bump, please have a look @rycee

**Review by trueNAHO — APPROVED** [review]
Without this patchset, `psd-resync.service` fails with `mkdir: command not found`, resulting in `psd` not working:

```console
$ systemctl status --user psd-resync.service
○ psd-resync.service - Timed profile resync
     Loaded: loaded (/home/<USER>/.config/systemd/user/psd-resync.service; enabled; preset: enabled)
     Active: inactive (dead) since [...]
TriggeredBy: ● psd-resync.timer
   Main PID: [487993] (code=exited, status=0/SUCCESS)
        CPU: 7ms

[...] systemd[1789]: Starting Timed profile resync...
[...] profile-sync-daemon[488000]: /nix/store/2d2c22cr9s56ib72m88yzp80255vzpfx-profile-sync-daemon-6.50/bin/profile-sync-daemon: line 105: mkdir: command not found
[...] profile-sync-daemon[487993]:  First time running psd so please edit /home/<USER>/.config/psd/psd.conf to your liking and run again.
[...] systemd[1789]: Finished Timed profile resync.
```

This patchset resolves this issue and allows `psd` to populate its required tmpfs.

**Comment by TheStachelfisch** [comment]
Closing in favor to creating a new pull request as the pipeline is clearly stuck and no manual feedback from someone with write access is expected.

**Pull request closed without merging**
