### PR TITLE
[backport 22.11] starship: condition nushell integration on nushell 0.73+

### PR DESCRIPTION
**Pull request by ncfavier**
Backporting https://github.com/nix-community/home-manager/pull/3776

### Checklist

- [X] Change is backwards compatible.

- [X] Code formatted with `./format`.

- [X] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [X] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

### CODE REVIEW

**Comment by ncfavier** [comment]
I don't know anything about nushell but that doesn't look like it's coming from home-manager. cc @Philipp-M

**Comment by rycee** [comment]
Looks like nushell 0.71 is the default in Nixpkgs 22.11? Doesn't this nushell integration therefore make Home Manager version 22.11 incompatible with Nixpkgs 22.11? If so, that's a bit embarrassing. Would be better if the integration could be made to work with nushell 0.71…

**Comment by ncfavier** [comment]
Yeah, I'm not sure why it was backported. It looks like this may not even be enough: https://github.com/starship/starship/pull/4477 is needed to avoid the above error with nushell 0.70+, but that PR is only in starship 1.12 while nixos-22.11 is on 1.11...

@Lord-Valen did you get this to work at all on 22.11? What versions of starship and nushell are you using?

**Comment by Philipp-M** [comment]
Yeah I agree with @rycee, maybe at least check the version of nushell and enable the integration for it based on the version of nushell instead of an assertion? And maybe add a warning that tells the user that starship doesn't work with nushell versions < 0.73 (if `programs.nushell.enable = true`) ?

**Comment by ncfavier** [comment]
I've reverted the PR on both branches. Not really in the right mindset to think about this, sorry.

**Pull request merged**
