### PR TITLE
firefox: use policies.json to install extensions

### PR DESCRIPTION
**Pull request by leo60228**
### Description

This probably isn't the cleanest way to write this code, but it does work. The benefit of this over sideloading is that the extensions are automatically enabled, and there aren't any warnings. The DisableAppUpdate policy normally comes from the system policies.json, which we override.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/rycee/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/rycee/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/rycee/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/rycee/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by leo60228** [comment]
Emacs tests are failing, but that looks like it's completely unrelated.

**Comment by eyJhb** [comment]
Seems like we are doing the same, I am however using a patch for Firefox, to allow this #1436 , and doing some other stuff regarding extensions :)

Maybe we could combine it into one?

**Comment by leo60228** [comment]
Nixpkgs doesn't include Firefox betas, so I use Mozilla's Nix overlay,
which wouldn't include this patch. I'd prefer it to be upstreamed.

**Comment by eyJhb** [comment]
Not sure how that is related to what I wrote above, as what you are currently doing with XDG_RUNTIME_DIR is possible with the current Firefox in nixpkgs.

Still, not sure what that comments mean regards the two PRs for this functionality in  HM

**Comment by leo60228** [comment]
I was referring to why I'd prefer the XDG_RUNTIME_DIR solution. It might've
made more sense as a comment on your PR.

**Comment by eyJhb** [comment]
Thinking of implementing both, as that would be fairly easy to give the choice :)

**Comment by eyJhb** [comment]
The same is now supported in the other PR, without all the rebuild, mkDerivation, etc. + individual policies if wanted.

**Comment by teto** [comment]
I will let @rycee comment on this since firefox configuration is his thing :D

**Comment by leo60228** [comment]
I'm still using this myself, but it's probably best to rewrite it based on https://github.com/NixOS/nixpkgs/pull/91724.

**Pull request closed without merging**
