### PR TITLE
mpd: allow using urls for musicDirectory

### PR DESCRIPTION
**Pull request by TotalChaos05**
### Checklist

- [x ] Change is backwards compatible.

- [ x] Code formatted with `./format`.

- [x ] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [x ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef). (none needed)

- [x ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC
@rembo10 
@emilazy

### CODE REVIEW

**Comment by rembo10** [comment]
LGTM :+1:

**Comment by teto** [comment]
I am not sure I get the change: do you just check the string is an URI ?

**Comment by TotalChaos05** [comment]
@teto it would only allow a path (or something convertible to it) earlier
this allows urls too

**Comment by TotalChaos05** [comment]
I forgot to commit after using `./format`
It should be fixed now

**Comment by rycee** [comment]
With `type = with types; either path str;`, shouldn't it already allow for strings such as `https://…`?

But perhaps it helps documentation to have a stricter type, but then would have to allow for `~/` as well considering the test error:

    error: A definition for option `services.mpd.musicDirectory' is not of type `path or string matching the pattern (http|https|nfs|smb)://.+'. Definition values:
    - In `/home/runner/work/home-manager/home-manager/tests/modules/programs/ncmpcpp-linux/ncmpcpp-issue-3560.nix': "~/music"

**Comment by TotalChaos05** [comment]
I think I was just really tired when I wrote this PR, because you are correct about it already allowing strings.
Apparently my issue was with mpdris2, because it only allows paths, and it gets auto-set with the value from `services.mpd.musicDirectory`

**Comment by rycee** [comment]
Fair enough, glad it got resolved in any case 🙂

**Pull request closed without merging**
