### PR TITLE
sway: fix workspace 10 missing from default config

### PR DESCRIPTION
**Pull request by emilylange**
### Description

workspace 10 is part of upstream's default config, but was missing in home-manager.

The initial "sway: add module" PR (#829, 02d60400035028d4c8affab24557344ca371b9fd) went through multiple iterations and had workspace 10 included for a brief moment. Until the author removed it in a force-push commenting

> Have removed the last change which added bound ${modifer}+0 to workspace number 10 as this messed up workspace numbering in sway.

https://github.com/nix-community/home-manager/pull/829#issuecomment-575087553

The reason might have been, that sway used to sort the workspaces in the order they appeared in the config.

Attribute sets in nix are sorted, but not "naturally sorted", meaning `bindsym Mod1+0 workspace number 10` comes before `bindsym Mod1+0 workspace number 1`.

It's unclear if that's what really happened. A workaround would have been to use `lib.lists.naturalSort` in `keybindingsStr`.

But I cannot reproduce this anymore in any way.
I assume this has been fixed many years ago by now.

upstream config: https://github.com/swaywm/sway/blob/020a572ed615b8fe272c7566a27ee0abe73a58d7/config.in#L113-L134

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC

@Scrumplex @alexarice @sumnerevans @SebTM @oxalica

### CODE REVIEW

**Review by rvolosatovs — APPROVED** [review]

**Review by SebTM — APPROVED** [review]
LGTM, another reason it might got left out is that the first defined workspace in keybindings is the workspace active when sway starts, but this can be controlled with defaultWorkspace already.

**Comment by Toomoch** [comment]
Somehow my Sway desktop is booting to workspace 10 always, and I can't seem to know why until I found this commit. Could it be the cause?
Here is my config: https://github.com/Toomoch/nixos-config/blob/testing/home/arnau/sway/default.nix

**Comment by SebTM** [comment]
Yes, but I don't see you using https://nix-community.github.io/home-manager/options.xhtml#opt-wayland.windowManager.sway.config.defaultWorkspace

correct? Then it's handled like explained here: https://github.com/nix-community/home-manager/pull/4636#pullrequestreview-1872565915

**Comment by Toomoch** [comment]
> Yes, but I don't see you using https://nix-community.github.io/home-manager/options.xhtml#opt-wayland.windowManager.sway.config.defaultWorkspace
> 
> correct? Then it's handled like explained here: [#4636 (review)](https://github.com/nix-community/home-manager/pull/4636#pullrequestreview-1872565915)

So sorry, I didn't even read the whole issue.  
That makes sense as number 10 is defined before number 1, see the config file home-manager built:
image
Using defaultWorkspace fixed it, thank you very much.

**Comment by Toomoch** [comment]
Maybe it would be a good idea to set it to 1 if using mkOptionDefault in the keybindings.

**Comment by philipwilk** [comment]
Hi, I've run into this as well - my default workspace being changed to 10. This is manageable on single display environments, where you can change the default workspace to be 1 explicitly, but this does not work with multi monitor setups. When i connect my laptop to a monitor, the laptop screen is workspace 1 but the monitor is workspace 10 instead of workspace 2. How could I workaround this?
If there is an option to set the default workspace for a specific monitor or resolution or something, I cannot use it, because I'm not using just one specific monitor; I'm using different ones across the uni, and I can't practically manually create a config for each one.

**Comment by philipwilk** [comment]
I'm not sure how to manually test it on my local machine without switching my hm input but i'd be up to try it

**Comment by emilylange** [comment]
hmm turns out throwing `lib.lists.naturalSort` at `keybindingsStr` is not as straight forward as I thought :(

**Comment by alexarice** [comment]
is it possible to add `mkAfter` to the workspace 10 bindings?

**Comment by Scrumplex** [comment]
Why don't we just set a default value for `defaultWorkspace`?

**Comment by emilylange** [comment]
> Why don't we just set a default value for `defaultWorkspace`?

Because it would not fix the ordering issue on multi-monitor setups. See https://github.com/nix-community/home-manager/pull/4636#issuecomment-1953468742

**Comment by michaelfranzl** [comment]
> The reason might have been, that sway used to sort the workspaces in the order they appeared in the config.

@emilylange I just tested it, and Sway still behaves like this. `defaultWorkspace` is not a workaround when using more than one monitor, because this will put workspace "10" to the second position.

**Pull request merged**
