### PR TITLE
dbus: pass absolute path of dbus-daemon to dbus-run-session

### PR DESCRIPTION
**Pull request by NickCao**
### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Review by oluceps — APPROVED** [review]

**Comment by oxalica** [comment]
This would expect that `dbus-daemon` is not started when `dbus-run-session` is called, and try to spawn `dbus-daemon` with the environment of `dbus-run-session`? Doesn't this spawned one conflict with user `dbus.service`, and have may-be-different envvars between every boot?

**Comment by oxalica** [comment]
I assume the main issue here is that `dconf` depends on the user `dbus.services`. Could we just move this dconf setup into a user service after `dbus`, and just reload/restart it during activation?

**Comment by tstachl** [comment]
@oxalica just jumping in here really quickly, this pull request solves an issue I ran into today. I'm currently pointing my flake input to @NickCao. So, while I appreciate your concern for future greatness, I think your suggestion should become an item on the todo list and this should be merged to mitigate an occurring issue.

**Comment by brianmcgee** [comment]
I am having trouble with https://github.com/danth/stylix applying GTK styles, activation script as failing with:

`dbus-run-session: failed to execute message bus daemon 'dbus-daemon': No such file or directory`

Switching my flake input to @NickCao's and all is good.

**Comment by NickCao** [comment]
Did a few experiments, and finds out that this issue only manifests when `programs.dconf.enable = false;` (nixos option).

**Comment by Myaats** [comment]
> Did a few experiments, and finds out that this issue only manifests when `programs.dconf.enable = false;` (nixos option).

I tried to set it to true (in nixos options), but dconf activation still fails on my device on boot. It executes without issues when I am already in a GNOME session and restart the home-manager-$USER service manually.
```
Nov 21 16:11:23 shun hm-activate-mats[879]: Starting Home Manager activation
Nov 21 16:11:23 shun hm-activate-mats[879]: Activating checkFilesChanged
Nov 21 16:11:23 shun hm-activate-mats[879]: Activating checkLinkTargets
Nov 21 16:11:23 shun hm-activate-mats[879]: Activating writeBoundary
Nov 21 16:11:23 shun hm-activate-mats[879]: Activating installPackages
Nov 21 16:11:23 shun hm-activate-mats[879]: Activating dconfSettings
Nov 21 16:11:23 shun hm-activate-mats[1318]: dbus-run-session: failed to execute message bus daemon 'dbus-daemon': No such file or directory
Nov 21 16:11:23 shun hm-activate-mats[1316]: dbus-run-session: EOF reading address from bus daemon
Nov 21 16:11:24 shun systemd[1]: home-manager-mats.service: Main process exited, code=exited, status=127/n/a
```

Unsure if this is a separate issue or not

**Comment by NickCao** [comment]
However the underlying issue is, as long as the current activation script runs into the else branch, it immediately fails. I think we should merge this and rethink about the logic around dconf in a separate issue.

**Comment by thiagokokada** [comment]
Would also be nice to backport this to release-22.11 if this is merged.

**Comment by rycee** [comment]
Thanks! Rebased to master in 02c05460339e5239ef6fc83eecea047e7e879704. Also cherry-picked to 22.11.

**Pull request closed without merging**
