### PR TITLE
zsh: add `completion.path`

### PR DESCRIPTION
**Pull request by 06kellyjac**
### Description

Let users set a different location to dump the zcompdump file.
Having `.zcompdump` in my zsh config dir was getting annoying.

**TODO**:

- [ ] This is currently a breaking change.
  - I could implement it as another option alongside the old `enableCompletion`?
  - or is there some method of aliasing `enableCompletion` to the new `completion.enable`?
- [ ] Is this a clean method of adding the `mkdir -p ...` & `-d ${cfg.completion.path}`?
  - I tried doing a couple `optionalString`s but it didn't look too good.
  - Open to any styling/structure advice.

### Checklist

- [ ] Change is backwards compatible.

- [X] Code formatted with `./format`.
  - `zsh.nix` isn't included but I tried to keep it formatted similar to the rest of the file.

- [X] Code tested through `nix-shell --pure tests -A run.all`.
  - All OK. Ended with `bash: PREEXEC_READY: unbound variable` though...

- [X] Test cases updated/added. See [example](https://github.com/rycee/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).
  - No existing completion related tests

- [X] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/rycee/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/rycee/home-manager/commits/master) for examples.

### CODE REVIEW

**Comment by berbiche** [comment]
I'm not sure how rycee handles renamed options, but I know Nix modules has [`mkRenamedOptionModule`](https://github.com/NixOS/nixpkgs/blob/5622b6b6feb669edc227aaf000413d5b593d4051/lib/modules.nix#L736-L754).

On another note, do you happen to know how `compinit -d` differs from `zstyle ':completion:*' cache-path "${config.xdg.cacheHome}/zsh/completion-cache"`?
I use the last one in my configuration.

**Comment by 06kellyjac** [comment]
@berbiche thanks for the reply

> On another note, do you happen to know how `compinit -d` differs from `zstyle ':completion:*' cache-path "${config.xdg.cacheHome}/zsh/completion-cache"`?
> I use the last one in my configuration.

I also use this setting. No idea if it does much but it's one of those I've picked up when looking for speed improvements.
My `zstyle ':completion:*' ...` cache file looks like the following:

```
modules=( ${(Q)"${(z)$(<<\EO:modules

EO:modules
)}"} )
modaliases=( ${(Q)"${(z)$(<<\EO:modaliases

EO:modaliases
)}"} )
```

That's the whole thing apparently.

my `.zcompdump` file is:
`......` marking a chunk removed to keep it short

```
#files: 2869	version: 5.8

_comps=(
'-' '_precommand'
'-*-' '_bootctl'
'.' '_source'
'5g' '_go'
'5l' '_go'
'6g' '_go'
'6l' '_go'
'8g' '_go'
'8l' '_go'
'a2dismod' '_a2utils'
'a2dissite' '_a2utils'
......
'zypper' '_zypper'
)

_services=(
'bzcat' 'bunzip2'
......
'zf_chown' 'chown'
)

_patcomps=(
'*/(init|rc[0-9S]#).d/*' '_init_d'
)

_postpatcomps=(
'c++-*' '_gcc'
'g++-*' '_gcc'
......
'yodl(|2*)' '_yodl'
'zf*' '_zftp'
)

_compautos=(
'_call_program' '+X'
)

zle -C _bash_complete-word .complete-word _bash_completions
zle -C _bash_list-choices .list-choices _bash_completions
zle -C _complete_debug .complete-word _complete_debug
zle -C _complete_help .complete-word _complete_help
zle -C _complete_tag .complete-word _complete_tag
zle -C _correct_filename .complete-word _correct_filename
zle -C _correct_word .complete-word _correct_word
zle -C _expand_alias .complete-word _expand_alias
zle -C _expand_word .complete-word _expand_word
zle -C _history-complete-newer .complete-word _history_complete_word
zle -C _history-complete-older .complete-word _history_complete_word
zle -C _list_expansions .list-choices _expand_word
zle -C _most_recent_file .complete-word _most_recent_file
zle -C _next_tags .list-choices _next_tags
zle -C _read_comp .complete-word _read_comp
bindkey '^X^R' _read_comp
bindkey '^X?' _complete_debug
bindkey '^XC' _correct_filename
bindkey '^Xa' _expand_alias
bindkey '^Xc' _correct_word
bindkey '^Xd' _list_expansions
bindkey '^Xe' _expand_word
bindkey '^Xh' _complete_help
bindkey '^Xm' _most_recent_file
bindkey '^Xn' _next_tags
bindkey '^Xt' _complete_tag
bindkey '^X~' _bash_list-choices
bindkey '^[,' _history-complete-newer
bindkey '^[/' _history-complete-older
bindkey '^[~' _bash_complete-word

autoload -Uz _a2ps _a2utils _aap _abcde _absolute_command_paths \
            _ack _acpi _acpitool _acroread _adb \
            _add-zle-hook-widget _add-zsh-hook _alias _aliases _all_labels \
            ......
            _zsocket _zstyle _ztodo _zypper _fast-theme
autoload -Uz +X _call_program

typeset -gUa _comp_assocs
_comp_assocs=( '' )
```

So it's pretty different :sweat_smile:
`wc -l` tells me it's 2472 lines long.
I've looked around for some `compinit` docs but I didn't find much. This was the most in-depth <http://zsh.sourceforge.net/Doc/Release/Completion-System.html>

**Comment by berbiche** [comment]
Ehh I never bothered to check if the zcompdump was written in the right place. As it turns out the file was being created in my $ZDOTDIR all along.

**Comment by teto** [comment]
sadly zsh doesn't follow xdg standard, would setting ZDOTDIR be enough for your usecase @06kellyjac ?

**Comment by 06kellyjac** [comment]
> sadly zsh doesn't follow xdg standard

I'm not sure I understand why that means I shouldn't change `compinit`'s output location

> would setting ZDOTDIR be enough for your usecase?

Sadly not. Setting `ZDOTDIR` just dumps the zcompdump file in there instead of home. But i want to change it to go to the xdg cache since it is a cache file.
If anything it would be better staying in HOME than the xdg config dir as that should only contain config, HOME is free real-estate.


This changing `compinit`'s output location is pretty common & what I used to do before I was using home-manager for my zsh config, but theres no way to do this with the current module setup.

<https://wiki.archlinux.org/index.php/XDG_Base_Directory>

The zsh entry in "hardcoded" goes over what you can change to make zsh a bit more respectful of xdg

**Comment by teto** [comment]
you could try the mkRenamedOptionModule indeed. I think this could even be enabled by default.

**Comment by berbiche** [comment]
`mkRenamedOptionModule` won't work in submodules until https://github.com/NixOS/nixpkgs/pull/97023 is merged.

**Comment by 06kellyjac** [comment]
I'll try and fix this up now the other PR is merged

**Pull request closed without merging**
