### PR TITLE
git: make ignore file the default for excludesFile

### PR DESCRIPTION
**Pull request by bobvanderlinden**
### Description

The option `programs.git.ignores` creates a file `~/.config/git/ignore`. However, this file is not used by git. Git doesn't read ignore files in `~/.config/git` as far as I could tell and thus the option does not do anything.

This PR attempts to make the ignore file be used by setting it as the `core.excludesFile` git configuration by default.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by berbiche** [comment]
According to `man git-config`:
> ```
> core.excludesFile
>           Specifies the pathname to the file that contains patterns to describe
>           paths that are not meant to be tracked, in addition to .gitignore
>           (per-directory) and .git/info/exclude. Defaults to
>           $XDG_CONFIG_HOME/git/ignore. If $XDG_CONFIG_HOME is either not set or
>           empty, $HOME/.config/git/ignore is used instead. See gitignore(5).
>```

**Comment by berbiche** [comment]
I use

``` nix
ignores = [
  ".vagrant/"
  "~."
  ".DS_STORE"
  "*.swp"
];
```

and these files are automatically ignored.

**Comment by bobvanderlinden** [comment]
Hmm, you are absolutely right. It seems there is a bug in vscode regarding global git ignore files. Thanks for the headsup :+1:

**Comment by berbiche** [comment]
@bobvanderlinden did your PR resolve your issue with vscode?

**Comment by bobvanderlinden** [comment]
No, it didn't. I was comparing vscode first with git status after and not thinking it through. Your comment reminded me of that.

I just found an option in vscode enable usage of global gitignore. It is disabled by default. So I just need to use that.

**Pull request closed without merging**
