### PR TITLE
programs.gpg: update references to respective manpages

### PR DESCRIPTION
**Pull request by foo-dogsquared**
### Description

The [document that is previously linked encourages to refer to the respective manpage that came with the package](https://gnupg.org/documentation/manpage.html) so I replace the references of the web version with the manpages.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [ ] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

This is only an update on the module option description so I didn't test the modules and only built the documents (e.g., `nix-build -A docs.html`, `nix-build -A docs.manPages`) to see how it looks.

### CODE REVIEW

**Comment by ncfavier** [comment]
Why not both? The `citerefentry` can link to the web page.

In NixOS we have [machinery](https://github.com/NixOS/nixpkgs/pull/208762) to make that happen automatically, but not here. One more reason to eventually make Home Manager use `nixosOptionsDoc`.

**Comment by foo-dogsquared** [comment]
> Why not both? The `citerefentry` can link to the web page.

I don't see any disadvantage to that so I can link both documents.

On the other hand, I didn't know `citerefentry` can do that. Although, I'm not able to make it work so I just applied with the `<link>` element. (I could be misunderstanding this but then again, I rarely use DocBook.)

> In NixOS we have [machinery](https://github.com/NixOS/nixpkgs/pull/208762) to make that happen automatically, but not here. One more reason to eventually make Home Manager use `nixosOptionsDoc`.

Thank you for bringing this to my attention. The outputs look nice in both web and manpages format (or at least in Neovim as my pager).

**Comment by ncfavier** [comment]
You can just wrap the `citerefentry` in a `link`:

```xml
<link xlink:href="https://gnupg.org/documentation/manpage.html">
  <citerefentry>...</citerefentry>
</link>
```

**Comment by foo-dogsquared** [comment]
> You can just wrap the `citerefentry` in a `link`:
> 
> ```
> <link xlink:href="https://gnupg.org/documentation/manpage.html">
>   <citerefentry>...</citerefentry>
> </link>
> ```

Thank you for the hint. I didn't realize `<link>` can contain other elements.

**Review by ncfavier — APPROVED** [review]

**Pull request merged**
