### PR TITLE
hypridle: Use After graphical-session.target instead of pre target

### PR DESCRIPTION
**Pull request by zoriya**
### Description

Before this, hypridle was running before graphical-session.target was started so it was missing the WAYLAND_DISPLAY var & could not start successfully. This PR adds a constraint to make hypridle start after the compositor, making sure WAYLAND_DISPLAY is available.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC

@khaneliman @fufexan

### CODE REVIEW

**Comment by rycee** [comment]
Are you certain this is necessary. I tried [setting up hypridle](https://git.sr.ht/~rycee/configurations/tree/8e1a3552cc25357500a3932b1fa26cb8eeea5377/item/user/common.nix#L1539-1568) and it seems to start just fine as-is. That said, for me the graphical-session.target is started by Hyprland itself using an `exec-once` in `hyprland.conf`. How do you start your compositor?

**Comment by zoriya** [comment]
My compositor is bound to graphical-session.target, I start it using `systemctl --user start river` using the new option I added in #5627

**Review by khaneliman — APPROVED** [review]

**Comment by zoriya** [comment]
@rycee How could we get this merged?

**Comment by fufexan** [comment]
Imo https://github.com/nix-community/home-manager/pull/6086 achieves the same result and is more ergonomic in case people use UWSM-managed sessions.

**Pull request closed without merging**
