### PR TITLE
neovim: Add option to configure plugins before they are loaded

### PR DESCRIPTION
**Pull request by i077**
### Description

This PR adds a new option `before` to the `pluginWithConfigType` used for the `programs.neovim.plugins` option.
The `config` option in this submodule allows the user to specify vimscript to configure a specific plugin, but this vimscript comes _after_ plugins are loaded (specifically they get appended to the end of the `customRC` input to [`vimrcContent`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vim-plugins/vim-utils.nix#L186) from `pkgs.vim-utils`). 
The new `before` option lets the user specify vimscript that comes _before_ plugins are loaded (and specifically is mapped to the `beforePlugins` input to `vimrcContent`).

This is needed for plugins that require users to specify certain options before the plugin itself is loaded. For example, vim-polyglot lets users disable certain language packs with `g:polyglot_disabled`, but [requires](https://github.com/sheerun/vim-polyglot#troubleshooting) that this option be declared before vim-polyglot itself is loaded. With this PR, if I wanted polyglot disabled for the LaTeX filetypes, I'd add
```nix
{
  programs.neovim.plugins = with pkgs.vimPlugins; [
    {
      plugin = vim-polyglot;
      before = "let g:polyglot_disabled = ['tex', 'latex']";
    }
  ];
}
```
to my home-manager config, and the line specified in `before` goes just after the `set nocompatible` line in the generated init.vim file. If I had instead declared that variable with `config` instead of `before`, that line would be at the very bottom, and the resulting neovim would display this warning at every startup:
image
whereas now, no such message is displayed.

I updated the relevant test to add a `before` option to a plugin, which adds a useless comment, and it passes on my end.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Review by berbiche — APPROVED** [review]
LGTM!

**Comment by teto** [comment]
with this https://github.com/nix-community/home-manager/pull/1652, I think we could without this PR, you could fill the config with normal vim  `home.file."${config.xdg.configHome}/nvim/...".text = "...";`

**Comment by i077** [comment]
> with this #1652, I think we could without this PR, you could fill the config with normal vim `home.file."${config.xdg.configHome}/nvim/...".text = "...";`

Hmm, I'm not sure how your PR necessarily conflicts with mine. If I wanted to manage vim plugins with home-manager and only define certain options if the plugin is present, wouldn't you still need `pluginWithConfigType`?

e.g. I don't want to have that `g:polyglot_disabled` variable defined if I remove vim-polyglot from my config, and I think the easiest way to store that dependency is with that type.

**Comment by i077** [comment]
(also bumping for @rycee since it seems like he's the one maintaining this module)

**Comment by i077** [comment]
Rebased on top of master & resolved any merge conflicts. Test is still passing.

**Comment by berbiche** [comment]
@teto @i077 hi, what is the status with this PR?

**Comment by i077** [comment]
@berbiche In my opinion this PR is ready to go. It works for me when I test it out, and gets rid of that error I mentioned in the PR. @teto mentioned that his PR (merged a few weeks ago) makes this one obsolete, but I wasn't really sure why.

I would still like to see this merged in, though.

**Comment by berbiche** [comment]
Sorry for the late response, I'll wait for @teto's opinion as I am not familiar with the vim/neovim packaging.

**Comment by teto** [comment]
sry for the delay, such plugins seem rare. I would like to experiment with a custom vimRc where one could insert the generated vimscript so that one can do 
```
neovim.customRc = 
" what comes before
let g:xxxx = 2
{{neovim.generatedVimrc}}
let g:xx_after = 3
```
In htis case, you cold maybe make polyglot optional and load it at the end of your vimrc via `packeradd! polyglot`.

**Comment by i077** [comment]
Hmm okay. I agree that this doesn't really happen with many plugins. I see how I'd do it with the `optional` option in `pluginWithConfigType`. Just for the sake of documentation here, seems like I'd do something like this to get something roughly equivalent to the original nix code in the PR message:

```nix
{
  programs.neovim.plugins = with pkgs.vimPlugins; [
    {
      plugin = vim-polyglot;
      optional = true;
      config = ''
        let g:polyglot_disabled = ['tex', 'latex']
        packadd! polyglot
      '';
    }
  ];
}
```

I will try this out right now to see if it achieves the same effect.

**Comment by i077** [comment]
Okay, seems like that works. This workaround is acceptable to me since this is kind of rare anyways, so I'm going to close this PR. Thanks everyone!

**Comment by teto** [comment]
cool !
Btw I have a working prototype for https://github.com/nix-community/home-manager/pull/1630#issuecomment-774972836 but outside your usecase I wonder if it s really useful xD

**Comment by i077** [comment]
I don't use the `programs.neovim.configure` option, I've been sticking with `plugins` and `extraConfig` [here](https://github.com/i077/system/blob/master/modules/editors/neovim/default.nix), so that wouldn't really apply to me.

**Comment by teto** [comment]
the config is generated from `plugins`so it wouldn't matter that you use configure or not.

**Pull request closed without merging**
