### PR TITLE
spotify-player: add support for actions

### PR DESCRIPTION
**Pull request by diniamo**
### Description

Add support for configuring actions added in the new [v0.19.1](https://github.com/aome510/spotify-player/releases/tag/v0.19.1) release.

@repparw

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

### CODE REVIEW

**Comment by repparw** [comment]
test failed, seems to be order of output in the file?
don't think is relevant for the program

**Comment by diniamo** [comment]
Society if CI only ran the relevant tests

**Comment by repparw** [comment]
@rycee can you have a look at this? Seems to be a quick merge I think

**Comment by repparw** [comment]
no news on this?

**Comment by diniamo** [comment]
Can't really do much

**Comment by rycee** [comment]
Thanks! Merged to master now 🙂

**Pull request merged**
