### PR TITLE
firefox: fix darwin NativeMessagingHostsPath

### PR DESCRIPTION
**Pull request by mlyxshi**
### Description

https://wiki.mozilla.org/WebExtensions/Native_Messaging

```
Mac 	User 	~/Library/Application Support/Mozilla/NativeMessagingHosts/<name>.json
Linux 	User 	~/.mozilla/native-messaging-hosts/<name>.json
```

Related: #4952 

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

### CODE REVIEW

**Comment by rycee** [comment]
Thanks! Looks good to me. Would you mind resolving the merge conflict?

CC @Lillecarl in case you have feedback.

**Comment by Lillecarl** [comment]
LGTM! 😃

**Comment by mlyxshi** [comment]
@rycee conflict solved. 
I'm not good at handle commit history when pr conflict. If you are not happy, I will open a new pr

**Comment by Lillecarl** [comment]
He can squash, but if you only wanna edit the last commit:

1. Stage your stuff (I use pkgs.gitui for staging) 
2. git commit --amend
3. git push -- force

**Comment by rycee** [comment]
Thanks! Merged to master now 🙂

**Pull request merged**
