### PR TITLE
vim: add option to specify pkgs.vim_configurable

### PR DESCRIPTION
**Pull request by arcnmx**
### Description

Feel free to suggest a better option name.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by arcnmx** [comment]
See also: #1745
Not sure why it died, but its discussion might contain useful suggestions for the option name.

**Review by berbiche — CHANGES_REQUESTED** [review]
Can we use `package` instead of `packageConfigurable` like all the other modules?
I understand that the name conveys the intent but for discoverability I prefer the former name.
We also have multiple modules that expect (un)wrapped packages and the information is provided in the documentation.

**Comment by arcnmx** [comment]
> Can we use `package` instead of `packageConfigurable` like all the other modules?

My only concern is that `programs.vim.package` is already used as an output of the wrapped package, so changing it like that would become a breaking change. Configs can currently refer to it like `EDITOR=${config.programs.vim.package}/bin/vim`, what should the wrapped output be called instead?
(note that I personally don't care if this becomes a breaking change, it just seemed less controversial to aim to make it backward-compatible)

> I understand that the name conveys the intent but for discoverability I prefer the former name.

I feel like one will have to consult the docs regardless when they want to set or use either variable, and will find them next to each other with clear explanations but *shrug*, it is common for `package` to be an input option so...

> We also have multiple modules that expect (un)wrapped packages and the information is provided in the documentation.

Are there any examples that can be used as a reference? Most do indeed use `package` as wrapped, some use unwrapped (neovim), but few if any seem to actually have wrapped package output options.

**Review by berbiche — APPROVED** [review]
Sorry for my silence. `packageConfigurable` is the least problematic name given the collision with `package`.

**Comment by berbiche** [comment]
We should probably make the `package` option `visible = false;` and rename it to `finalPackage` with `mkRenamedOptionModule`.

**Pull request merged**
