### PR TITLE
modules/neovim: fix config generation

### PR DESCRIPTION
**Pull request by khaneliman**
### Description

Just trying to fix the recent breakage with config generation, follow up to https://github.com/NixOS/nixpkgs/pull/344541. @teto  would like you to sanity check me here... 

### Checklist

- [ ] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC
@rycee @teto

### CODE REVIEW

**Comment by teto** [comment]
not sure if you took a peek at https://github.com/nix-community/home-manager/pull/5964 but that looks correct ;) if tests are good then we're good. My PR does a bit more so it is probably best to fix the problem at hand with your PR.

**Comment by khaneliman** [comment]
> not sure if you took a peek at #5964 but that looks correct ;) if tests are good then we're good. My PR does a bit more so it is probably best to fix the problem at hand with your PR.

Yeah, I saw the other before when we first noticed checks failing. Didn’t know if you still had work to do on that so threw together a bandaid

**Comment by tmiller** [comment]
@teto This appears to work for me.

**Comment by teto** [comment]
once again thank you . I failed to edit the commit message on merge but next time, try to provide more details please :p

**Pull request merged**
