### PR TITLE
docs: bump nmd

### PR DESCRIPTION
**Pull request by rycee**
### Description

- Introduces support for Markdown documentation in modules.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

### CODE REVIEW

**Comment by oxalica** [comment]
This introduces IFD on https://gitlab.com/rycee/nmd/-/blob/master/lib/modules-doc.nix#L63, and breaks the evaluation where IFD is disabled.

**Comment by ncfavier** [comment]
Also the conversion script doesn't seem to support RST roles, so alias options look awkward: https://nix-community.github.io/home-manager/options.html#opt-xsession.pointerCursor.package

Will try to fix this later

**Comment by ncfavier** [comment]
> This introduces IFD on [gitlab.com/rycee/nmd/-/blob/master/lib/modules-doc.nix#L63](https://gitlab.com/rycee/nmd/-/blob/master/lib/modules-doc.nix#L63), and breaks the evaluation where IFD is disabled.

PR'd a fix https://gitlab.com/rycee/nmd/-/merge_requests/9

**Comment by ncfavier** [comment]
> Also the conversion script doesn't seem to support MyST roles, so alias options look awkward: [nix-community.github.io/home-manager/options.html#opt-xsession.pointerCursor.package](https://nix-community.github.io/home-manager/options.html#opt-xsession.pointerCursor.package)

Actually it supports them fine, the problem is that https://github.com/NixOS/nixpkgs/pull/208407 changes `mkAliasOptionModule` to not use `mdDoc` without actually changing the description. cc @pennae, we should make `mkAliasOptionModule` emit an actual DocBook description.

But I guess Home Manager can use `mkAliasOptionModuleMD` now that we support Markdown descriptions.

**Pull request merged**
