### PR TITLE
docs: fix standalone (path-based) install instructions

### LINKED ISSUE #487: file 'home-manager' was not found in the Nix search path
```
$ nix-shell '<home-manager>' -A install
error: file 'home-manager' was not found in the Nix search path (add it using $NIX_PATH or -I)
```

Hi, I receive the above when trying to install home manager.

### LINKED ISSUE #1267: 'home-manager/home-manager/home-manager.nix' was not found
I've installed home-manager on a NixOS (20.03) machine. Created `~/.config/nixpkgs/home.nix` with:

```
{ pkgs, ... }:
  {
    home.packages = [
      pkgs.zsh
    ];
    programs.home-manager = {
      enable = true;
    };
  }
```

When I run `home-manager switch`, I get:

```
error: file 'home-manager/home-manager/home-manager.nix' was not found in the Nix search path (add it using $NIX_PATH or -I)
error: file 'home-manager/home-manager/home-manager.nix' was not found in the Nix search path (add it using $NIX_PATH or -I)
/home/thraxil/.nix-profile/bin/home-manager: line 115: /tmp/home-manager-build.g5ojUtbBWB/news-info.sh: No such file or directory
```

There is one generation:

```
$ home-manager generations
2020-05-24 11:43 : id 1 -> /nix/store/nny0wvx0sc4d1h79n6y28px9p7icfgrr-home-manager-generation
```

I can't uninstall either:

```
$ home-manager uninstall
This will remove Home Manager from your system.
Really uninstall Home Manager? [y/n] y
Switching to empty Home Manager configuration...
error: file 'home-manager/home-manager/home-manager.nix' was not found in the Nix search path (add it using $NIX_PATH or -I)
error: file 'home-manager/home-manager/home-manager.nix' was not found in the Nix search path (add it using $NIX_PATH or -I)
/home/thraxil/.nix-profile/bin/home-manager: line 115: /tmp/home-manager-build.CmjOsZgBIy/news-info.sh: No such file or directory
```

Any idea on what's wrong and what I can do to fix it? I'm pretty new to Nix

### LINKED ISSUE #2564: bug: cannot install home-manager
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

This is the command I execute.

```bash
nix-shell '<home-manager>' -A install
```

The result is here.

```bash
Creating initial Home Manager generation...

/nix/store/i9zl4x42wwkjy2gbj749aci3y25f4r94-home-manager/bin/home-manager: line 73: NIX_PATH: unbound variable
Uh oh, the installation failed! Please create an issue at

    https://github.com/nix-community/home-manager/issues

if the error seems to be the fault of Home Manager.
```

### Maintainer CC

_No response_

### System information

```markdown
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.2.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4`
 - channels(tuampon): `"home-manager"`
 - channels(root): `"nixpkgs-22.05pre338556.fc58c3761e9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

### LINKED ISSUE #3091: bug: Unable to install home-manager (NixOS, standalone)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Hello,

on a VPS, built with NixOS 21.11, I updated the channel to 22.05, rebuilt, then changed my configuration.nix to have a user
then on this user, I add the channel for home-manager 22.05 and update it.

but when I do "nix-shell '<home-manager>' -A install" I get : 
error: file 'home-manager' was not found in the Nix search path (add it using $NIX_PATH or -I)

I tried to reboot the vps, nothing. Also ssh into root and then do su myuser, but this shouldn't cause issue.

I tried to mess around with $NIX_PATH but then it would return a permission error

It does work if I add the channel to the root and install with it, but afaik the manual says to use a standard user, at least for the standalone install

(no, I don't want to update home-manager through nixos-rebuild)

thanks a lot for this awesome tool

### Maintainer CC

_No response_

### System information

```markdown
- system: `"x86_64-linux"`                      - host os: `Linux 5.15.53, NixOS, 22.05 (Quokka), 22.05.1627.4aceab3cadf`                       - multi-user?: `no`                             - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(niels): `"home-manager-22.05.tar.gz"`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

(idk why it says no to multi-user, bc I have root and a user "niels")
```

### LINKED ISSUE #4071: bug: Install steps do not produce an install without work-arounds
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

# Background
Similar to #487 
On a totally fresh install of NixOS 23.05 (a few minutes ago, clean config from the GUI install), as one of the very first things I did, I ran:
```
nix-channel --add https://github.com/nix-community/home-manager/archive/release-23.05.tar.gz home-manager
nix-channel --update
nix-shell '<home-manager>' -A install
```
And I see the same error as on #487.

```
error: file 'home-manager' was not found in the Nix search path (add it using $NIX_PATH or -I)
```

I'm opening this now as I've failed to get this basic case working now on three (3) separate installations on as many different pieces of hardware.
The first, I tried on 22.05 and assumed it was because I was too new to Nix or customized myself into a corner. The second I assumed it was because I was *highly* configured even from the default install on old hardware with lots of edges. Today's copy of 23.05, however, I'm no longer a newbie and I didn't config a thing. Alas, it doesn't work again :upside_down_face:

# Question to answer
Is there a step about adding a folder to NIX_PATH that is *required* to use home-manager missing from the docs?

# Proposed Fix
Update the docs with this answer above

### Maintainer CC

_No response_

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.05 (Stoat), 23.05.533.c37ca420157`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(bujiraso): `"home-manager-23.05.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by eclairevoyant**
### Description

Don't depend on `NIX_PATH` being correctly set during the installation process.

Fixes #4071, fixes #3091, fixes #2564, fixes #1267, fixes #487. See NixOS/nix#2033.

### Checklist

- [ ] Change is backwards compatible.

- [ ] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

### CODE REVIEW

**Comment by rycee** [comment]
Thanks! Looks quite nice and simple. I guess this wouldn't work if home-manager was added as a system channel (under `/nix/var/nix/profiles/per-user/root/channels`). But perhaps it is OK to assume that it is a user channel considering the nix-channel add command above is shown as a user command. I'll ponder it.

**Comment by rokonio** [comment]
It should be noted that for users that have `use-xdg-base-directories` enabled, `~/.nix-defexpr` is located in `$XDG_STATE_HOME`/nix/defexpr or `$HOME/.local/state/nix/defexpr`

**Comment by eclairevoyant** [comment]
sure, I can make the command uglier

or I can assume that everyone who uses that option has opted in and should know its effects well enough (and have enough nix knowledge) that spoonfeeding the exact command might be overkill

**Comment by canadaduane** [comment]
Thank you for this. As a new nixos user, it was confusing to get `file 'home-manager' was not found in the Nix search path` while trying to install for first time.

**Pull request closed without merging**
