### PR TITLE
khard: add option to contact module for khard dir

### LINKED ISSUE #4531: bug: Incompatibility between vdirsyncer and khard modules
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I have enabled both khard and vdirsyncer programs. The idea is that vdirsyncer fetches&uploads the contacts that are listed&edited with khard.

It seems that it isn't possible to have both vdirsyncer and khard configured together with home-manager because:
1. vdirsyncer creates a subfolder within `accounts.contact.accounts.<name>.local.path` and puts the vcf files in the subfolder.
2. khard reads the vcf files from `accounts.contact.accounts.<name>.local.path` directly and doesn't look recursively inside the subfolders.
As a result, khard finds no vcf files and thus lists no contacts.

Said differently, here is part of my vdirsyncer configuration:

```ini
[storage contacts_nico_local]
fileext = ".vcf"
path = "~/configuration/contacts"
```

and here is part of my *working* hand-written khard configuration:

```ini
[addressbooks]
[[contacts]]
path = ~/configuration/contacts/172ce...
```

As you can see, the configuration file references the subfolder `172ce.../` instead of directly the path configured for vdirsyncer.

Here is an excerpt of what home-manager generates for khard:

```ini
[addressbooks]
[[nico]]
path = ~/configuration/contacts
```

This doesn't work because of the missing subfolder.

Here is the home-manager configuration that I cannot use:

```nix
{ pkgs, lib, ... }:

{
  programs.vdirsyncer = { enable = true; };

  programs.khard = {
    enable = true;
    settings = {
      ...
    };
  };

  accounts.contact.accounts = {
    nico = {
      vdirsyncer = {
        enable = true;
        ...
      };
      khard = { enable = true; };
      local = {
        path = "~/configuration/contacts";
        ...
      };
      remote = { ... };
    };
  };
}
```

### Maintainer CC

@olmokramer @antonmosich @teto @ayyess @loewenheim @jorsn 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.5.5-200.fc38.x86_64, Fedora Linux, 38 (Workstation Edition), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixpkgs"`
 - channels(temp): `"home-manager, nixpxkgs"`
 - channels(cassou): `"home-manager-22.11.tar.gz, nixpkgs"`
 - nixpkgs: `/home/cassou/Documents/projects/nix-system/nixpkgs`
```

### PR DESCRIPTION
**Pull request by octvs**
- Add an extra option, `accounts.contact.accounts.<name>.khard.defaultCollection` to hardcode a subdir for khard to function as intended.
  - Khard expects to be given a collection directory directly, from which there can be multiple of in a vdir. This contrasts khal or vdirsyncer which support recursive search.

Fixes #4531

### Description

Details can be found on the commit msg. This is my first time trying to contribute, thus I appreciate any feedback & shown patience.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- ~~If this PR adds a new module~~

   - ~~[ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).~~

#### Maintainer CC

@olmokramer @antonmosich

### CODE REVIEW

**Comment by octvs** [comment]
Referring to [this change](https://github.com/nix-community/home-manager/pull/5217#discussion_r1548748932) @sumnerevans 

My config fails to build with: 
```sh
      error: lib.path.subpath.join: Element at index 0 is not a valid subpath string:
           The given string "/home/<redacted>" starts with a `/`, representing an absolute path
```

Considering the `accounts.contact.accounts.<name>.local.path` is also a [string](https://github.com/nix-community/home-manager/blob/80546b220e95a575c66c213af1b09fe255299438/modules/accounts/contacts.nix#L12-L13), wouldn't it make sense to keep it the way it was before with `lib.strings.concatStringsSep`?

**Comment by octvs** [comment]
I've used `builtins.toPath` on the resulting path instead, now it passes the tests without further changes.

**Comment by sumnerevans** [comment]
Ah, I think that maybe https://noogle.dev/f/lib/path/append is better then.

**Comment by octvs** [comment]
I can incorporate `lib.path.append` to the logic with the following block

```nix
xdg.configFile."khard/khard.conf".text = let
  getPath = acc:
    if (acc.khard.defaultCollection != "") then
      (lib.path.append (/. + acc.local.path) acc.khard.defaultCollection)
    else
      acc.local.path;
in ''
  [addressbooks]
  ${lib.concatMapStringsSep "\n" (acc: ''
    [[${acc.name}]]
    path = ${getPath acc}
  '') (lib.attrValues accounts)}

  ${renderSettings cfg.settings}
'';
```

which passes the tests, but the resulting path will be in the nix store.
Testing on my config:

```sh
$ cat .config/khard/khard.conf | head -n 3 | tail -n 1
path = /nix/store/0mh5j53f4s8k5bnl1z555pa5rd6xyn9x-default
```

Don't we want it to point to a user specified path?

**Comment by sumnerevans** [comment]
does 

```
 (lib.path.append acc.local.path acc.khard.defaultCollection)
```

not work?

Basically, I just want to avoid having to implement the check for trailing `/` in `acc.local.path`

**Comment by octvs** [comment]
>  (lib.path.append acc.local.path acc.khard.defaultCollection)
As stated, it results in a path in the store.

> Basically, I just want to avoid having to implement the check for trailing
> `/` in `acc.local.path`
I think `toPath` sanitizes it already.

I made some quick tests about this, I don't know the policy about the tests so
I'm just attaching it, if desired I can commit them as well.

**Comment by octvs** [comment]
[test.txt](https://github.com/nix-community/home-manager/files/14858646/test.txt)

**Comment by sumnerevans** [comment]
Ah, if `toPath` is already sanitizing, then that's good enough. Sorry for the running around in circles on this.

It would be good to add a test of the new option here: https://github.com/nix-community/home-manager/tree/master/tests/modules/programs/khard

**Comment by octvs** [comment]
> Ah, if `toPath` is already sanitizing, then that's good enough. 
I can't find more info to back this, since `toPath` got deprecated[1]. I have
replaced it with `toString (/. + stringVariable)` which shows the same
behaviour, inspired by [similar changes on nixpkgs][2].

> It would be good to add a test of the new option here:
> https://github.com/nix-community/home-manager/tree/master/tests/modules/programs/khard
That I'm aware already, as seen on the patch above. I wasn't sure whether it is
okay to copy an existing test and bend it around as I did.  Anyhow, I will
include the tests I wrote.

I would rather squash all of them to a single proper commit before it gets
merged so I would appreciate a heads up before, so I can squash once at the
end. Otherwise I'm spamming the issue I've linked on the commit message.

> Sorry for the running around in circles on this.
Not at all! The feedback is much appreciated. Even further comments from you or
others are welcome, it helps my learning process.

[1]: https://github.com/NixOS/nix/commit/0bea4a50e035c06805ac65360b1b50d3681e4f87
[1]: https://github.com/NixOS/nixpkgs/commit/6da6accd303be776bb4e958da52046da86f9cb5c

**Comment by olmokramer** [comment]
I've never gotten vdirsyncer collections to work, but it looks like this will keep working when you are not using collections and don't set the `defaultCollection` option. So I'm fine with merging this as is :+1: (although I cannot merge this myself).

**Review by olmokramer — APPROVED** [review]

**Comment by rycee** [comment]
Thanks! Merged to master now.

**Pull request merged**
