### PR TITLE
hyprland: do not override existing plugins settings in config

### PR DESCRIPTION
**Pull request by SamueleFacenda**
The plugin setting in the hyprland config is used both for defining plugin paths and configuring the plugins. This fix removes the silent override of the plugins settings converting them to the `plugin:<name> { ...settings }` syntax.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC
@fufexan

### CODE REVIEW

**Comment by fufexan** [comment]
Defining plugin paths should not be done through `settings.plugin`, but through the `plugins` option. I haven't had issues with that setup.

However, if you've tested this and it works, then it looks good to me.

**Comment by SamueleFacenda** [comment]
Yes sorry. I mean that plugin settings are defined via `settings.plugin.<pluginname>` and this option is overwitted by the `plugin` option generated from `hyprland.plugins`.

**Comment by rycee** [comment]
I sort of think I understand what is going on here, and agree with @fufexan that it seems reasonable. But I would like to see `tests/modules/services/window-managers/hyprland/simple-config.nix` updated to show it more concretely (and to avoid future regressions).

**Comment by SamueleFacenda** [comment]
Ok. I updated the test.

**Comment by rycee** [comment]
Thanks! Merged to master now 🙂

**Comment by SamueleFacenda** [comment]
Great, thanks!

**Pull request merged**
