### PR TITLE
ranger: add module

### PR DESCRIPTION
**Pull request by fpob**
### Description

Add module `programs.ranger`

Supersedes #3264 

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

### CODE REVIEW

**Comment by rycee** [comment]
Thanks! Sorry for the delay. Merged to master now 🙂

**Comment by leoperegrino** [comment]
@fpob Thank you for the work in this module. Right now, the ranger `scope.sh` is not configurable and there is no way to enable pdf and video preview, since those sections are commented out by default. Do you think you could/think it's a good idea implement something like https://github.com/NixOS/nixpkgs/pull/70432? or help me out with it?

**Comment by fpob** [comment]
@leoperegrino You can use `overrideAttrs` to customize the `scope.sh` in the ranger package. For example, to enable pdf preview:

```nix
  programs.ranger = {
    enable = true;
    package = pkgs.ranger.overrideAttrs (prev: {
      propagatedBuildInputs = prev.propagatedBuildInputs ++ [
        pkgs.poppler_utils
      ];
      preConfigure = prev.preConfigure + ''
        sed -r -e '/#.*application\/pdf\)$/,/.*;;$/s/#//' -i ranger/data/scope.sh
      '';
    });
    # ...
```

**Comment by leoperegrino** [comment]
@fpob That worked great! Thanks for the help!

**Pull request merged**
