### PR TITLE
services.batsignal: init

### PR DESCRIPTION
**Pull request by Kranzes**
### Checklist

- [ ] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [x] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by ncfavier** [comment]
Dupe of https://github.com/nix-community/home-manager/pull/3243

**Comment by Kranzes** [comment]
> Dupe of #3243

I like my implementation much more personally, imo https://github.com/nix-community/home-manager/pull/3243 is too intrusive, and tries to handle too much.

**Comment by loicreynier** [comment]
I'm fine with both implementations. I personally prefer having the specific options available in the HM module but it's true that it would be better to let the program handle its defaults. I could set to `null` the defaults in my implementation to let the program handle the defaults. Concerning the maintainability, since the program is pretty mature, I don't think it will really be an issue.

**Comment by Kranzes** [comment]
If you're fine with both then I definitely want mine merge instead ;)

**Comment by ncfavier** [comment]
I'm inclined towards this implementation, though ideally for a program whose main mode of configuration is command-line arguments we'd want a middle ground between a "stringly-typed" `extraArgs` and hardcoding every flag as an option. Something like an [RFC 42](https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md)-style `pkgs.formats.cli` powered by [`toGNUCommandLine`](https://github.com/NixOS/nixpkgs/blob/master/lib/cli.nix), but this isn't a thing yet :shrug:

**Comment by rycee** [comment]
Thanks! Merged to master now.

**Pull request merged**
