### PR TITLE
joplin-desktop: support profiles and more options

### PR DESCRIPTION
**Pull request by zorrobert**
### Description

Joplin supports creating multiple profiles. This functionality was previously missing from the joplin-desktop module and is implemented in this PR.

In order to support profiles, the structure of the defined options had to be split up into "global" settings that are shared between profiles and profile-specific settings. This is a breaking change, but a small one and necessary to avoid confusion about the difference between global and profile-specific settings.

In addition to profiles, a few new options (such as markdown settings) have been added.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

#### Maintainer CC

@rycee

### CODE REVIEW

**Comment by zorrobert** [comment]
@rycee This is ready for merge, please review. The test failure seems unrelated.

**Comment by zorrobert** [comment]
Hi, could you please review and merge this?
@ncfavier @teto @sumnerevans @rycee

**Comment by zorrobert** [comment]
@rycee @teto @sumnerevans @ncfavier @khaneliman 

Is there something left to do before this can be merged? If you don't have the time to review or merge it now, that is fine, I would just like to know if there is any news on this.

**Comment by khaneliman** [comment]
> @rycee @teto @sumnerevans @ncfavier @khaneliman
> 
> Is there something left to do before this can be merged? If you don't have the time to review or merge it now, that is fine, I would just like to know if there is any news on this.

Sorry, I still don't have merge rights in home-manager.

**Comment by zorrobert** [comment]
Since I opened this PR things have changed a bit and I want to rework and improve parts of this. I will close this PR and open a new one once I'm done.

**Pull request closed without merging**
