### PR TITLE
systemd: use sd-switch

### PR DESCRIPTION
**Pull request by rycee**
### Description

This makes the systemd module use the sd-switch application to perform the unit switch during a generation activation.

Since the closure of sd-switch is relatively lightweight we unconditionally pull it in as a dependency. We simultaneously remove the `systemd.user.startServices` option and perform the switch action automatically.

This is the second attempt at introducing this change, the first being 9c0fe3957bb91128d5d3599e289fe9344a293ece, which was quickly reverted 223e3c38a13fb45726c7a9d97e2612ae53ab4f98 since the feature didn't work on systems where the user is not given a functional dbus session. Since the user session is now always socket activated, see https://github.com/NixOS/nixpkgs/pull/97801, we can (hopefully) safely reintroduce the feature.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

### CODE REVIEW

**Comment by rycee** [comment]
@misuzu Are you still using HM on a headless system using Nixpkgs unstable? If so would you mind giving this branch a try? Nixpkgs unstable should use a socket activated user dbus session since a while back so in principle it should work to communicate with systemd over dbus even on headless systems…

**Comment by misuzu** [comment]
@rycee it still has the same issue as in https://github.com/nix-community/home-manager/pull/1388#issuecomment-668460320

home-manager: https://github.com/nix-community/home-manager/commit/ed73bf80c3b3920e05e9a2656314f66df7bb9139
nixpkgs: https://github.com/NixOS/nixpkgs/commit/a322b32e9d74fb476944ff6cfb55833dc69cfaaa
```
$ RUST_BACKTRACE=full VERBOSE=1 DRY_RUN=1 /nix/store/16jcj9dddl2i7l5n2r03php7svvjgydb-home-manager-generation/activate
Starting home manager activation
Sanity checking Nix
warning: unknown setting 'extra-sandbox-paths'
warning: unknown setting 'extra-sandbox-paths'
Sanity checking oldGenNum and oldGenPath
This is a dry run
Using Nix version: warning: unknown setting 'extra-sandbox-paths'
nix-env (Nix) 2.4pre20201102_550e11f
Activation variables:
  oldGenNum=140
  oldGenPath=/nix/store/16jcj9dddl2i7l5n2r03php7svvjgydb-home-manager-generation
  newGenPath=/nix/store/16jcj9dddl2i7l5n2r03php7svvjgydb-home-manager-generation
  newGenNum=141
  newGenGcPath=/nix/var/nix/gcroots/per-user/misuzu/current-home
  genProfilePath=/nix/var/nix/profiles/per-user/misuzu/home-manager
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
warning: unknown setting 'extra-sandbox-paths'
Activating linkGeneration
Cleaning up orphan links from /home/misuzu
Checking /home/misuzu/.piknik.toml: exists
Checking /home/misuzu/.config/mc/ini: exists
Checking /home/misuzu/.config/fontconfig/conf.d/10-hm-fonts.conf: exists
Checking /home/misuzu/.config/broot/conf.toml: exists
Checking /home/misuzu/.config/broot/launcher/installed-v1: exists
Checking /home/misuzu/.config/git/ignore: exists
Checking /home/misuzu/.config/git/config: exists
Checking /home/misuzu/.config/htop/htoprc: exists
Checking /home/misuzu/.config/starship.toml: exists
Checking /home/misuzu/.ssh/config: exists
Checking /home/misuzu/.zshrc: exists
Checking /home/misuzu/.cache/.keep: exists
Checking /home/misuzu/.dir_colors: exists
Checking /home/misuzu/.tmux.conf: exists
No change so reusing latest profile generation 140
Creating home file links in /home/misuzu
mkdir -p --verbose /home/misuzu
ln -nsf --verbose /nix/store/l5asmap4b39aipzhimdagfmkaw3ahix8-home-manager-files/.piknik.toml /home/misuzu/.piknik.toml
mkdir -p --verbose /home/misuzu/.config/mc
ln -nsf --verbose /nix/store/l5asmap4b39aipzhimdagfmkaw3ahix8-home-manager-files/.config/mc/ini /home/misuzu/.config/mc/ini
mkdir -p --verbose /home/misuzu/.config/fontconfig/conf.d
ln -nsf --verbose /nix/store/l5asmap4b39aipzhimdagfmkaw3ahix8-home-manager-files/.config/fontconfig/conf.d/10-hm-fonts.conf /home/misuzu/.config/fontconfig/conf.d/10-hm-fonts.conf
mkdir -p --verbose /home/misuzu/.config/broot
ln -nsf --verbose /nix/store/l5asmap4b39aipzhimdagfmkaw3ahix8-home-manager-files/.config/broot/conf.toml /home/misuzu/.config/broot/conf.toml
mkdir -p --verbose /home/misuzu/.config/broot/launcher
ln -nsf --verbose /nix/store/l5asmap4b39aipzhimdagfmkaw3ahix8-home-manager-files/.config/broot/launcher/installed-v1 /home/misuzu/.config/broot/launcher/installed-v1
mkdir -p --verbose /home/misuzu/.config/git
ln -nsf --verbose /nix/store/l5asmap4b39aipzhimdagfmkaw3ahix8-home-manager-files/.config/git/ignore /home/misuzu/.config/git/ignore
mkdir -p --verbose /home/misuzu/.config/git
ln -nsf --verbose /nix/store/l5asmap4b39aipzhimdagfmkaw3ahix8-home-manager-files/.config/git/config /home/misuzu/.config/git/config
mkdir -p --verbose /home/misuzu/.config/htop
ln -nsf --verbose /nix/store/l5asmap4b39aipzhimdagfmkaw3ahix8-home-manager-files/.config/htop/htoprc /home/misuzu/.config/htop/htoprc
mkdir -p --verbose /home/misuzu/.config
ln -nsf --verbose /nix/store/l5asmap4b39aipzhimdagfmkaw3ahix8-home-manager-files/.config/starship.toml /home/misuzu/.config/starship.toml
mkdir -p --verbose /home/misuzu/.ssh
ln -nsf --verbose /nix/store/l5asmap4b39aipzhimdagfmkaw3ahix8-home-manager-files/.ssh/config /home/misuzu/.ssh/config
mkdir -p --verbose /home/misuzu
ln -nsf --verbose /nix/store/l5asmap4b39aipzhimdagfmkaw3ahix8-home-manager-files/.zshrc /home/misuzu/.zshrc
mkdir -p --verbose /home/misuzu/.cache
ln -nsf --verbose /nix/store/l5asmap4b39aipzhimdagfmkaw3ahix8-home-manager-files/.cache/.keep /home/misuzu/.cache/.keep
mkdir -p --verbose /home/misuzu
ln -nsf --verbose /nix/store/l5asmap4b39aipzhimdagfmkaw3ahix8-home-manager-files/.dir_colors /home/misuzu/.dir_colors
mkdir -p --verbose /home/misuzu
ln -nsf --verbose /nix/store/l5asmap4b39aipzhimdagfmkaw3ahix8-home-manager-files/.tmux.conf /home/misuzu/.tmux.conf
Activating onFilesChange
Activating reloadSystemd
Options are Options {
    dry_run: true,
    verbose: true,
    timeout: None,
    old_dir: Some(
        "/nix/store/16jcj9dddl2i7l5n2r03php7svvjgydb-home-manager-generation/home-files/.config/systemd/user",
    ),
    new_dir: "/nix/store/16jcj9dddl2i7l5n2r03php7svvjgydb-home-manager-generation/home-files/.config/systemd/user",
}
Performing dry-run
Enabling verbose output
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DBus(D-Bus error: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11 (org.freedesktop.DBus.Error.NotSupported))', src/lib.rs:349:66
stack backtrace:
   0:     0x5609db15d87c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6f05017bae98a16f
   1:     0x5609db17923d - core::fmt::write::h4e423e63ef6952a5
   2:     0x5609db156ef5 - std::io::Write::write_fmt::h87a2ee7a0f0be87a
   3:     0x5609db14ebb0 - std::panicking::default_hook::{{closure}}::hcb146b886903f1b9
   4:     0x5609db14e8fa - std::panicking::default_hook::hce9df2b42299e608
   5:     0x5609db14f193 - std::panicking::rust_panic_with_hook::h71db2d7d0653eadb
   6:     0x5609db15dcc9 - std::panicking::begin_panic_handler::{{closure}}::h59f65871c4ccd803
   7:     0x5609db15d9cc - std::sys_common::backtrace::__rust_end_short_backtrace::hedd2b2fd0e04e8bb
   8:     0x5609db14eda2 - rust_begin_unwind
   9:     0x5609db178f21 - core::panicking::panic_fmt::h810a06353f831f07
  10:     0x5609db178fb3 - core::result::unwrap_failed::hf16cbd16a77f8bf3
  11:     0x5609db11cb8b - sd_switch::switch::he137768f7d21416b
  12:     0x5609db1142bf - sd_switch::main::hbdf8cc5940964a28
  13:     0x5609db114d23 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb5f81623617ecda5
  14:     0x5609db114d39 - std::rt::lang_start::{{closure}}::h5dd9599a00391764
  15:     0x5609db14f4f4 - std::rt::lang_start_internal::hab5cf64ec2394616
  16:     0x5609db114c92 - main
  17:     0x7fe143878dbd - __libc_start_main
  18:     0x5609db1130ba - _start
  19:                0x0 - <unknown>
```

**Comment by peterhoeg** [comment]
Even if dbus is socket activated, we would still have to have *something* listening on that socket and sd-switch to know the path to said socket. What is `$DBUS_SESSION_BUS_ADDRESS` in this case where it blows up?

**Comment by misuzu** [comment]
> Even if dbus is socket activated, we would still have to have _something_ listening on that socket and sd-switch to know the path to said socket. What is `$DBUS_SESSION_BUS_ADDRESS` in this case where it blows up?

```
$ echo $DBUS_SESSION_BUS_ADDRESS
unix:path=/run/user/1000/bus
$ ls -l /run/user/1000/bus
srw-rw-rw- 1 misuzu users 0 Nov 13 14:26 /run/user/1000/bus
```

**Comment by rycee** [comment]
Thanks for testing @misuzu! Quite curious result, there isn't really anything in the activation script that would unset or change the `DBUS_SESSION_BUS_ADDRESS` variable so I'm not certain why sd-switch wouldn't see the socket. I will have to ponder this a bit and perhaps try setting up a headless VM to test in.

**Comment by archseer** [comment]
This is a headless thing: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=690530#15

Without X11 or Wayland running you apparently need to manually start the dbus session.

**Comment by rycee** [comment]
@archseer Thanks, that's an interesting find. It's a quite old mail though, I wonder if it still applies for systemd socket activation? Seems to me that systemd would be able to keep track of the session sufficiently to avoid the problem of duplicate dbus daemons.

**Comment by rycee** [comment]
I've tried setting up a headless virtualbox with unstable NixOS and this HM branch and it does seem to socket activate the user dbus session OK:

sd-switch-vbox

That said, this is not truly a headless system I guess since it still has a virtual console but DISPLAY is definitely unset, at least. I will do a few more experiment to see if I can reproduce the error.

**Comment by rycee** [comment]
I've made a few more tries at reproducing the problem, without much luck. So I'll park this PR again until I'm able to sink more time into the session dbus hole.

**Comment by rycee** [comment]
Switched to #1656, which adds sd-switch as a third option to the existing two. Will remove the two others some time in the future when the headless situation has been figured out.

**Pull request closed without merging**
