### PR TITLE
Refactor four tests to conform to nixpkgs TOML/YAML changes

### LINKED ISSUE #6049: bug: 4 home-manager tests broken by recent nixpkgs update
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

At some point since the last successful flake.lock update a change to nixpkgs seems to have changed how certain files in the TOML and YAML filetype gety generated.

This results in 4 test cases failing:
<details>
<summary>alacritty-merging-settings</summary>

```
alacritty-merging-settings: FAILED
Expected home-files/.config/alacritty/alacritty.toml to be same as /nix/store/3vva42k10x0v1cwpz77rl6fx46d3r2x8-settings-toml-expected.toml but were different:
--- actual
+++ expected
@@ -1,3 +1,4 @@
+[font]
 [font.bold]
 family = "SFMono"
 
For further reference please introspect /nix/store/dlhsx7z20izbzbscknqxfgaigddksvqz-nmt-report-alacritty-merging-settings
```
</details>
<details>
<summary>alacritty-toml-config</summary>

```
alacritty-toml-config: FAILED
Expected home-files/.config/alacritty/alacritty.toml to be same as /nix/store/3vva42k10x0v1cwpz77rl6fx46d3r2x8-settings-toml-expected.toml but were different:
--- actual
+++ expected
@@ -1,3 +1,4 @@
+[font]
 [font.bold]
 family = "SFMono"
 
For further reference please introspect /nix/store/cbp0z54h15y0zbsj8kf4f6d4sc354xz9-nmt-report-alacritty-toml-config
```
</details>
<details>
<summary>espanso-basic-configuration</summary>

```
espanso-basic-configuration: FAILED
Expected home-files/.config/espanso/match/base.yml to be same as /nix/store/ayhphlwrw71hcay8iq97p68zmn720fb8-basic-matches.yaml but were different:
--- actual
+++ expected
@@ -10,7 +10,9 @@
 matches:
 - replace: It's {{currentdate}} {{currenttime}}
   trigger: :now
-- replace: "line1\nline2"
+- replace: 'line1
+
+    line2'
   trigger: :hello
 - regex: :hi(?P<person>.*)\.
   replace: Hi {{person}}!
For further reference please introspect /nix/store/agjrp2lrk880qnwad2iihzc8cniw0jh9-nmt-report-espanso-basic-configuration
```
</details>
<details>
<summary>spotify-player-settings</summary>

```
spotify-player-settings: FAILED
Expected home-files/.config/spotify-player/theme.toml to be same as /nix/store/i6imsp1kp42ikphsq3yc5bhv4pd07h5i-theme.toml but were different:
--- actual
+++ expected
@@ -1,6 +1,7 @@
 [[themes]]
 name = "default2"
 
+[themes.component_style]
 [themes.component_style.block_title]
 fg = "Magenta"
 
For further reference please introspect /nix/store/nzag3700di81hnx8jv9s6f377yi5ci1r-nmt-report-spotify-player-settings
```
</details>

This mirrors home-manager-bots failed flake.lock update from today: [CI link](https://github.com/nix-community/home-manager/actions/runs/11696945756/job/32574876595?pr=6048)

The first nixpkgs that I tried was 7ffd9ae656aec493492b44d0ddfb28e79a1ea25 from my PRs own [bump commit](https://github.com/RedEtherbloom/home-manager/commit/3c057e67fbd9eabd979813bf55424a0d22bb9a0c) yesterday.

### Maintainer CC

Alacritty TOML: @r-vdp 
Espanso YAML: @liyangau 
Spotify-Player TOML: @diniamo 

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 6.11.6, NixOS, 24.11 (Vicuna), 24.11.20241102.7ffd9ae`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.24.9`
- channels(root): `"nixos"`
- nixpkgs: `/nix/store/zq2axpgzd5kykk1v446rkffj3bxa2m2h-source`
```

### PR DESCRIPTION
**Pull request by RedEtherbloom**
### Description

We briefly refactored the tests for three modules to conform to, mostly cosmetic, changes to how TOML and YAML are generated by nixpkgs.
We also had to update the flake.lock to test the changes, as the nixpkgs update happened some time since the last flake.lock update and home-manager-bot couldn't update master since, because of the broken test.

Closes #6049.
Makes #6048 redundant.
Removes implicit blocker of #6042.

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes. 

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC

Alacritty TOML: @r-vdp
Espanso YAML: @liyangau
Spotify-Player TOML: @diniamo

### CODE REVIEW

**Review by r-vdp — APPROVED** [review]
LGTM!

**Comment by RedEtherbloom** [comment]
> Hey, let's undraft this PR already, the CI will run the tests anyway and we don't want to block anyone.
>
> 2min later: Tests finished, all OK
:smile:

**Comment by liyangau** [comment]
LGTM

**Review by diniamo — APPROVED** [review]

**Review by dawidd6 — APPROVED** [review]

**Review by GaetanLepage — APPROVED** [review]

**Comment by rycee** [comment]
Thanks! Merged to master now 🙂

**Pull request merged**
