### PR TITLE
hyfetch: add module

### PR DESCRIPTION
**Pull request by lilyinstarlight**
### Description

Adds a simple module for [hyfetch](https://github.com/hykilpikonna/hyfetch), which is in nixpkgs now (NixOS/nixpkgs#182944)

I've not actually contributed a module before and this one is pretty minimal, but I think I covered everything I saw in the contribution docs (except a news item which I'm happy to add if desired). Let me know if I'm missing something though!

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [x] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [x] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by rycee** [comment]
Thanks! Merged to master now. It is typically best if the person that does the merge adds the news entry, then we avoid unnecessary merge conflicts.

**Comment by luxus** [comment]
it doesn't work with the default config. after the setup assistant it runs into a logical permission error.
the defaults should have settings populated

**Comment by lilyinstarlight** [comment]
> it doesn't work with the default config. after the setup assistant it runs into a logical permission error. the defaults should have settings populated

I'm not at my computer at the moment (so can't test), but to clarify are you just doing `{ programs.hyfetch.enable = true; }` and getting the error?

**Comment by luxus** [comment]
yes, because the default is a `{}` empty file it tries to setup with the setup assistant and cannot write the file at the end
with this it works:
```
  programs.hyfetch = {
    enable = true;
    settings = {
      preset = "rainbow";
      mode = "rgb";
      color_align = {
        mode = "horizontal";
      };
    };
  };
```

**Comment by lilyinstarlight** [comment]
I'll make a PR when I get home to have it not write the config file if settings is empty (I might default it to `null` for that case and add a conditional)

Thank you for letting me know!

**Comment by rycee** [comment]
Something like

```
xdg.configFile."hyfetch.json" = mkIf (cfg.settings != {}) {
  source = jsonFormat.generate "hyfetch.json" cfg.settings;
};
```

may work.

**Comment by lilyinstarlight** [comment]
Yep that's roughly what I was thinking @rycee. I'll make the change later and add a test for it too when I'm at my computer again in a few hours

**Pull request merged**
