### PR TITLE
borgmatic: fix service permissions (#5749)

### PR DESCRIPTION
**Pull request by sdaqo**
### Description
This fixes the permissions of the borgmatic service. Please see #5749  for further info

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC
@DamienCassou

### CODE REVIEW

**Comment by DamienCassou** [comment]
Thank you for the PR. It seems that the tests don't pass:

```
$ nix-shell --pure tests -A run.borgmatic-service-basic-configuration
...
borgmatic-service-basic-configuration: FAILED
Expected /nix/store/kix0h311qfmk3wy0py3rv0flrhdycd9b-nmt-report-borgmatic-service-basic-configuration/normalized/borgmatic.service to be same as /nix/store/mci7093pbw5k441r6cah5mwvdsmafbmm-basic-configuration.service but were different:
--- actual
+++ expected
@@ -1,4 +1,5 @@
 [Service]
+CPUSchedulingPolicy=batch
 ExecStart=/nix/store/00000000000000000000000000000000-systemd/bin/systemd-inhibit \
   --who="borgmatic" \
   --what="sleep:shutdown" \
```

I believe `tests/modules/services/borgmatic/basic-configuration.service` should be changed accordingly.

**Comment by sdaqo** [comment]
Whoops I forgot to commit that file.

**Comment by DamienCassou** [comment]
Can you please squash your 2 commits into 1?

**Comment by sdaqo** [comment]
done

**Review by DamienCassou — APPROVED** [review]
I approve the changes.

**Comment by rycee** [comment]
Thanks! Merged to master now 🙂

**Pull request merged**
