### PR TITLE
i3-sway: multiple outputs

### PR DESCRIPTION
**Pull request by sevenautumns**
Multiple outputs can be assigned to a workspace.
Before #4059 assigning multiple outputs to a workspace was possible via:  
```nix
{
  output = "'HDMI' 'DVI'";
  workspace = "1";
}
```

Now the following needs to be used:
```nix
{
  output = "HDMI\" \"DVI";
  workspace = "1";
}
```

For resolving this issue, `output` can now also be a list of strings 

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC
@Scrumplex 
@alexarice 
@sumnerevans

### CODE REVIEW

**Review by Scrumplex — APPROVED** [review]
Code LGTM

**Comment by sevenautumns** [comment]
@Scrumplex sorry, ive made a small change to make the `let outputs` in `modules/services/window-managers/i3-sway/lib/functions.nix` more readable. Could you check one more time?

**Review by Scrumplex — APPROVED** [review]

**Review by Scrumplex — APPROVED** [review]
toLists is very elegant :D

**Comment by sevenautumns** [comment]
Thanks, I think now there is no way to optimize it more

**Comment by wucke13** [comment]
Excellent change, LGTM!

**Review by wucke13 — APPROVED** [review]

**Comment by sevenautumns** [comment]
Could I ask you for a review @ncfavier ?

**Review by ncfavier — APPROVED** [review]
Looks reasonable

**Comment by ncfavier** [comment]
macos tests should succeed once https://nixpk.gs/pr-tracker.html?pr=242954 turns all green

**Pull request merged**
