### PR TITLE
sway: indent sway configuration options

### PR DESCRIPTION
**Pull request by lulu-berlin**
The sway configuration maps attrsets into configuration blocks in the sway configuration files (typically ~/.config/sway/config).

The options nested inside curly braces are usually indented with 2 spaces, like is the case for `mode` (see: `modeStr` in [modules/services/window-managers/i3-sway/lib/functions.nix](https://github.com/nix-community/home-manager/blob/master/modules/services/window-managers/i3-sway/lib/functions.nix#L49)).

Nonetheless, some other configuration blocks are not indented, so it results looking like this:

```
output "eDP-1" {
position 0 0
resolution 1536x960@120Hz
}
```

rather than:

```
output "eDP-1" {
  position 0 0
  resolution 1536x960@120Hz
}
```

This PR fixes the indentation for `input`, `output` and `seat`.

### Checklist

- [x] Change is backwards compatible.

- [X] Code formatted with `./format`.

- [X] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [X] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [X] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC

@SebTM @alexarice @rycee

### CODE REVIEW

**Comment by lulu-berlin** [comment]
I have no idea why the macos test is failing and I don't have a macos machine to test it on.

If this failure is related to my PR and not just a flaky test, I'll be happy to adapt my PR to fix it, but I don't know what I'm supposed to do.

**Comment by SebTM** [comment]
> I have no idea why the macos test is failing and I don't have a macos machine to test it on.

Don't think it's related they fail on `master`as well ✌🏻

**Comment by lulu-berlin** [comment]
Thanks for the reassurance, @SebTM. :slightly_smiling_face: 

Do you have any feedback on my PR?

**Review by sumnerevans — APPROVED** [review]

**Comment by sumnerevans** [comment]
Seems fine. I can't merge due to the build failure as it's a required job and I can't override that, will have to wait for @rycee.

**Comment by rycee** [comment]
Thanks! Merged to master now 🙂

**Comment by lulu-berlin** [comment]
Thank you, @rycee!

**Pull request merged**
