### PR TITLE
[20.09] neovim: mark plugins as optional (possibly)

### PR DESCRIPTION
**Pull request by thiagokokada**
### Description

Backport #1559 so we can have a easier migration path for Neovim users in the next release.

See discussion here #1806.

### Checklist

- [x] Change is backwards compatible.

- [ ] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by thiagokokada** [comment]
Tested this in my personal fork of Home Manager (that is based on `release-20.09` but with multiples backported patches). Seems to work fine.

https://github.com/thiagokokada/home-manager/commit/6515778512b28ddcbc8b2692bb85642dcaa7ed45

**Comment by teto** [comment]
cc @rycee  who is the boss when it comes to backports :p 

If you already have your own fork with patches why upstream this ? There is always the risk it generates problems.

**Comment by thiagokokada** [comment]
@teto To help other uses to migrate. Most of them can't maintain their own fork (lack of skills, etc).

**Comment by teto** [comment]
thats laudable but if people choose the tagged release its because they favor stability over upgrades/features so it seems contradictory ?

**Comment by thiagokokada** [comment]
> thats laudable but if people choose the tagged release its because they favor stability over upgrades/features so it seems contradictory ?

Well, I think that small PRs like this one if they don't break backwards compatibility they should be fine, and I already tested it.

But if you're strongly against it I can close this PR, I was just trying to be helpful.

**Comment by teto** [comment]
i know thanks for the contributions btw  ;) and sorry for breaking your neovim. 
I just think this is not worth it. I jsut always use unstable so maybe it's best for some other users to chime in,

**Comment by rycee** [comment]
Perhaps can skip this PR for now but resurrect it if more people show interest/need for this patch to reach stable? Generally speaking backports have been mainly limited to bugs but I'm not completely against other things if it is safe and sufficiently desired by people.

**Comment by thiagokokada** [comment]
Ok, seems fair enough.

I will close this PR for now, if someone shows interest on it I can reopen it later.

**Pull request closed without merging**
