### PR TITLE
thunderbird: Implement `extensions` for profiles

### PR DESCRIPTION
**Pull request by booxter**
Closes: #5654

### Description

This is a near verbatim transplant of firefox option to thunderbird module. With it, I was able to deploy thunderbird profile with an extension pre-installed.

### Checklist

- [X] Change is backwards compatible.

- [ ] Code formatted with `./format`.

- [ ] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [X] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

### CODE REVIEW

**Comment by Mikilio** [comment]
A thing to note or documented should be that most get their Firefox add-ons from @rycee 's NUR repository.
I personally use something like this in my email home-manager module:
``` nix
let

  inherit (config.nur.repos.rycee.firefox-addons) buildFirefoxXpiAddon;
  extensionPath = "extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}";
  extensions = [
    (buildFirefoxXpiAddon {
      pname = "thunderAI";
      version = "v2.2.0pre5";
      addonId = "thunderai@micz.it";
      url = "https://github.com/micz/ThunderAI/releases/download/v2.2.0pre5/thunderai-v2.2.0pre5.xpi";
      sha256 = "NSEMCAlVWH22sY0Z5zEYltrbU8CS1RdG5CXIxerpJh0=";
      meta = { };
    })
    (buildFirefoxXpiAddon {
      pname = "languagetool";
      version = "8.11.2";
      addonId = "languagetool-mailextension@languagetool.org";
      url = "https://addons.thunderbird.net/thunderbird/downloads/file/1031394/grammatik_und_rechtschreibprufung_languagetool-8.11.2-tb.xpi";
      sha256 = "gBaKJIXjPtchXTNUKTRjD9iZ2OSqZGlw7xMjjsaK8rw=";
      meta = { };
    })
  ];

in
  ...
```
This should be added somewhere so people don't get confused on how to use this feature.
Even better, someone builds a CI similar to rycee's NUR for the thunderbird extension registry, at least for the official releases.

**Comment by booxter** [comment]
@Mikilio yeah I wasn't sure which example to give since AFAIU there are no packaged extensions. :) (I use a similar pattern as yours.) But yes I agree we should at least refer to the `buildFirefoxXpiAddon` if we don't have a better thing to suggest at the moment. I will see what I can do.

**Comment by dvaerum** [comment]
Hey @booxter, I have been using this for 2 weeks now 😃 and cannot wait for it to be merged 😉

Currently, I have using 3 plugins.

One is `languagetool` which I just pull in directly from `nur.repos.rycee.firefox-addons` and the 2 others I create using `buildFirefoxXpiAddon`.

```nix
tb_ext_owl-for-exchange = config.nur.repos.rycee.firefox-addons.buildFirefoxXpiAddon rec {
  pname = "owl-for-exchange";
  version = "1.3.4";
  addonId = "owl@beonex.com";
  url = "https://addons.thunderbird.net/user-media/addons/_attachments/986325/eule_fur_exchange-${version}-tb.xpi";
  sha256 = "4962b4efc0bc86cfe7f0ecaea2ddc3574ed28afa8003e8395ce80c747f26ffcc";
  meta = with lib;
  {
    homepage = "https://www.beonex.com/owl/";
    description = "Allows you to use your Exchange and Office365 email account using Outlook Web Access (OWA) with Thunderbird.";
    license = licenses.unfree;
    mozPermissions = [];
    platforms = platforms.all;
  };
};

tb_ext_cardbook = config.nur.repos.rycee.firefox-addons.buildFirefoxXpiAddon rec {
  pname = "cardbook";
  version = "97.5";
  addonId = "cardbook@vigneau.philippe";
  url = "https://addons.thunderbird.net/user-media/addons/_attachments/634298/cardbook-${version}-tb.xpi";
  sha256 = "d2bef178398979d7e0e055b1259c59995302e4151bf471146073c1bbd88cc657";
  meta = with lib;
  {
    homepage = "https://gitlab.com/CardBook/CardBook";
    description = "This add-on allows you to manage all your contacts under the vCard standard.";
    license = licenses.mpl20;
    mozPermissions = [];
    platforms = platforms.all;
  };
};
```

Just want to share 😁

**Comment by teto** [comment]
maybe rebase to retrigger CI

**Comment by rycee** [comment]
Thanks! Merged to master now 🙂

**Comment by dvaerum** [comment]
> Very nice, thank you! But can someone please explain how to extract all the metadata, like `addonId`, `sha256`, etc.?

Of course, here is a guide. Need this add-on, so I wanted to write down the steps too 😁

1. Go to (I used Firefox): https://addons.thunderbird.net/en-US/thunderbird/
2. Search for your plugin you want and select it. I picked [HTML Source Editor](https://addons.thunderbird.net/en-US/thunderbird/addon/html-source-editor)
3. Click on the "Download Now" button and wait for the download to finish
4. Click on the "Copy Download Link and show in the picture. I got `https://addons.thunderbird.net/user-media/addons/_attachments/988542/html_source_editor-1.6-tb.xpi?filehash=sha256%3A3db2bffe668555daff7095b08224f6c57eb3a05aea0eabddfd575b012abae6f4`
image
5. Removed everything in the URL, which comes after `?` (including `?`). So in this case `?filehash=sha256%3A3db2bffe668555daff7095b08224f6c57eb3a05aea0eabddfd575b012abae6f4` and the URL is now clean. This is the download link: `https://addons.thunderbird.net/user-media/addons/_attachments/988542/html_source_editor-1.6-tb.xpi`
6. Now that you have downloaded the file, use what ever archive tool you prefer to exact the `manifest.json` file from `xpi` file, I use this command `unzip -p 'html_source_editor-1.6-tb.xpi' 'manifest.json` to print the `manifest.json` file to stdout in my terminal.
**Note:** The `xpi` file is just a zip file.
```bash
file html_source_editor-1.6-tb.xpi 
# html_source_editor-1.6-tb.xpi: Zip archive data, at least v2.0 to extract, compression method=deflate
```
7. Now to fine all the information
```nix
buildFirefoxXpiAddon rec {
  # Use the name from the downloaded files and replace `_` with `-`
  pname = "html-source-editor";

  # Look in the `manifest.json` output at json path `.version`
  version = "1.6";

  # Look in the `manifest.json` output at json path `.applications.gecko.id`
  addonId = "edithtmlsource@jobisoft.de";

  # Insert the download line and replace the `1.6` (the version number) with `${version}`.
  url = "https://addons.thunderbird.net/user-media/addons/_attachments/988542/html_source_editor-${version}-tb.xpi";

  # Run the command `sha256sum 'html_source_editor-1.6-tb.xpi'` to get the hash value of the downloaded file.
  sha256 = "4962b4efc0bc86cfe7f0ecaea2ddc3574ed28afa8003e8395ce80c747f26ffcc";
  meta = with lib;
  {
    # Get this URL from the link `Add-on home page` on the addons page there you clicked the "Download Now" button
    homepage = "https://github.com/jobisoft/HtmlSourceEditor";

    # Get this description from the section `About this Add-on` on the addons page there you clicked the "Download Now" button
    description = "Allows to edit the source of the currently composed message. A simple alternative to ThunderHTMLedit.";

    # In the `xpi` file next to the `manifest.json` file is a file named `LICENSE`, read it. It will tell you the license.
    license = licenses.mpl20;

    # Look in the `manifest.json` output at json path `.permissions`
    mozPermissions = [
      "compose"
      "menus"
    ];

    # The platform should just be `platforms.all` because I addons are not platforms specific as I understand it.
    platforms = platforms.all;
  };
};
```

**Comment by booxter** [comment]
@dvaerum I wonder if this should be dropped into a document and added to the repo, maybe? I suspect this may be confusing for users. Let me know what you think.

**Comment by dvaerum** [comment]
> @dvaerum I wonder if this should be dropped into a document and added to the repo, maybe? I suspect this may be confusing for users. Let me know what you think.

Make sense, but I am not sure there to drop it. That is mainly why I dropped it here. Do you have any suggestions @booxter ?

**Comment by Mikilio** [comment]
Actually, nixpkgs also has an interface now for packaging extensions and it also works with non-flake repos as flake inputs (like the 'latest' URLs from the store) and has a simpler interface than rycees solution. 

I can see a future where nixpkgs also provides outputs for all indexed extensions because of this.

My point being: let's mark this as a BETA feature or something and let it fix itself.

**Comment by jolars** [comment]
> Hey @booxter, I have been using this for 2 weeks now 😃 and cannot wait for it to be merged 😉
> 
> Currently, I have using 3 plugins.
> 
> One is `languagetool` which I just pull in directly from `nur.repos.rycee.firefox-addons` and the 2 others I create using `buildFirefoxXpiAddon`.
> 
> ```nix
> tb_ext_owl-for-exchange = config.nur.repos.rycee.firefox-addons.buildFirefoxXpiAddon rec {
>   pname = "owl-for-exchange";
>   version = "1.3.4";
>   addonId = "owl@beonex.com";
>   url = "https://addons.thunderbird.net/user-media/addons/_attachments/986325/eule_fur_exchange-${version}-tb.xpi";
>   sha256 = "4962b4efc0bc86cfe7f0ecaea2ddc3574ed28afa8003e8395ce80c747f26ffcc";
>   meta = with lib;
>   {
>     homepage = "https://www.beonex.com/owl/";
>     description = "Allows you to use your Exchange and Office365 email account using Outlook Web Access (OWA) with Thunderbird.";
>     license = licenses.unfree;
>     mozPermissions = [];
>     platforms = platforms.all;
>   };
> };
> 
> tb_ext_cardbook = config.nur.repos.rycee.firefox-addons.buildFirefoxXpiAddon rec {
>   pname = "cardbook";
>   version = "97.5";
>   addonId = "cardbook@vigneau.philippe";
>   url = "https://addons.thunderbird.net/user-media/addons/_attachments/634298/cardbook-${version}-tb.xpi";
>   sha256 = "d2bef178398979d7e0e055b1259c59995302e4151bf471146073c1bbd88cc657";
>   meta = with lib;
>   {
>     homepage = "https://gitlab.com/CardBook/CardBook";
>     description = "This add-on allows you to manage all your contacts under the vCard standard.";
>     license = licenses.mpl20;
>     mozPermissions = [];
>     platforms = platforms.all;
>   };
> };
> ```
> 
> Just want to share 😁

Hey @dvaerum , I see that you are using the owl extension here. Were you able to set up accounts for it declaratively in some way? For me, accounts set up manually (imperatively) with owl disappear on each new nixos rebuild.

**Comment by dvaerum** [comment]
> Hey @dvaerum , I see that you are using the owl extension here. Were you able to set up accounts for it declaratively in some way? For me, accounts set up manually (imperatively) with owl disappear on each new nixos rebuild.

Hey @jolars, I'm having the same problem as you hand I sadly have not been able to crack this one, and it is not for lag of trying 😅
Currently, I have been looking at the Owl code (luckily, the author is a gentleman, there have made the plugin source available even through the license is close). And trying to figure out which condition there isn't fulfilled since the Owl add-on keeps removing the account (or at least I believe that it is the Owl add-on).
Currently, my belief is that the solution lies with the add-ons own setting because using a debugger and set the account IDs to the hash which nix home-manager module generates, I was able to manually add an Owl account which survives a reboot, but that is still no reproducible. Sadly, I have no experience with developing Firefox or Thunderbird plugins, and I cannot figure out how or there I should set the breakpoint in the debugger for it to stop the Owl plugin at its "main" function, so I slowly can walk through the code and find the condition which I believe exist in Owl that removes the account and modify it to a condition which login into the account.
If you, @jolars (or anyone else for that matter), by any change know how to do this, I would love to learn from you/work with you on it 😇

**Comment by jolars** [comment]
> > Hey @dvaerum , I see that you are using the owl extension here. Were you able to set up accounts for it declaratively in some way? For me, accounts set up manually (imperatively) with owl disappear on each new nixos rebuild.
> 
> Hey @jolars, I'm having the same problem as you hand I sadly have not been able to crack this one, and it is not for lag of trying 😅 Currently, I have been looking at the Owl code (luckily, the author is a gentleman, there have made the plugin source available even through the license is close). And trying to figure out which condition there isn't fulfilled since the Owl add-on keeps removing the account (or at least I believe that it is the Owl add-on). Currently, my belief is that the solution lies with the add-ons own setting because using a debugger and set the account IDs to the hash which nix home-manager module generates, I was able to manually add an Owl account which survives a reboot, but that is still no reproducible. Sadly, I have no experience with developing Firefox or Thunderbird plugins, and I cannot figure out how or there I should set the breakpoint in the debugger for it to stop the Owl plugin at its "main" function, so I slowly can walk through the code and find the condition which I believe exist in Owl that removes the account and modify it to a condition which login into the account. If you, @jolars (or anyone else for that matter), by any change know how to do this, I would love to learn from you/work with you on it 😇

I see, yes I was guessing that this would be complicated. Thanks for the description of what you've done so far. Surviving a reboot would still be a definite improvement for me, so thanks for that. I'll let you know if I come across a solution. We should probably not pollute this PR discussion any further about this issue, which is largely unrelated, so I'll stop the discussion here, but I'll contact you if I manage to solve this.

**Pull request merged**
